### ISSUE TITLE
Bad Request when opening transports

### ISSUE THREAD

**Issue by zsstrehli** [marcellourbani/vscode_abap_remote_fs#102]
I got "Error 400:Bad Request"  message when I try to open the list of transports.
The connection to the system seems okay, at least I can open files and also open sapgui by pressing 'F5'.

Is it a bug or something is missing from the config file?

**Comment by marcellourbani** [comment]
Probably a bug.
Transport management comes in 2 or 3 flavours, works ok in 7.50 ... 7.52, doesn't with 7.30 or cloud platform...

What version of basis/abap are you running?

**Comment by zsstrehli** [comment]
It's on NW 7.81.

**Comment by marcellourbani** [comment]
Afraid I won't have access to that in a long time!
If you feel like you can log http and/or method calls in mongoose and send me a dump (watch out for sensitive data)
```json
...
"trace": {
        "mongoUrl": "mongodb://127.0.0.1:27017",
        "http_calls": true,
        "api_methods": true
      }
...
```
or you can do the same in eclipse and send me the relevant request from the abap communication log. Don't promise anything though. Cloud platform also have a completely different transport API btw, perhaps that will work if/ when I will implement t

**Comment by marcellourbani** [comment]
btw, just seen the same in my 7.50 system, I suspect it's from the git view

**Comment by marcellourbani** [comment]
Looks like it's a bug in the ADT plugin.
For some reason the rest router looks up /abapgit/repos rather than /repos

**Comment by zsstrehli** [comment]
@marcellourbani Thanks for the investigation.
Can you report the bug somehow to the ADT plugin developers?

**Comment by marcellourbani** [comment]
Still me :) ...and other 2 really

**Comment by zsstrehli** [comment]
Ohh, that's cool :)
