### ISSUE TITLE
Getting Unauthorized error, even when using the correct password

### ISSUE THREAD

**Issue by dellagustin-sap** [marcellourbani/vscode_abap_remote_fs#103]
Hello,

thanks for the great extension!

This problem is kind of solved, but there may be some kind of password "caching" bug.
I setup a connection, first with the wrong password (by mistake) for system ABC (example), and got an Unauthorized error message. 

After changing to the correct password (tested several times), kept getting the Unauthorized error.
I then setup system DEF, with the correct password, it worked.

I then tried again to connect with ABC, but without any change in config, it worked.

I did not try to reproduce it, but is it possible that the password is somehow cached, and that caused the issue?

Best Regards,
Guilherme Dellagustin.

**Comment by marcellourbani** [comment]
Hi Guilherme
It does try to remember passwords, but it's supposed to only do so after a successful connection.
And update it after another login
Anyway you can remove it with the right command:

![image](https://user-images.githubusercontent.com/2453277/79505009-a5183e80-802b-11ea-9179-af72872642a4.png)
Let me know if it fixes it
