### ISSUE TITLE
unable to resolve workspace folder

### ISSUE THREAD

**Issue by soydepr** [marcellourbani/vscode_abap_remote_fs#122]
getting this error after migrating to new laptop 

unable to resolve workspace folder

**Comment by marcellourbani** [comment]
never saw this one.
Did you migrate configurations/workspaces from the old one?
What OS are you running?

**Comment by soydepr** [comment]
running windows 10 
also see this error 
![image](https://user-images.githubusercontent.com/546367/92601359-b5e77c00-f27a-11ea-964b-0b7e5cce98cc.png)

**Comment by soydepr** [comment]
> never saw this one.
> Did you migrate configurations/workspaces from the old one?
> What OS are you running?

I migrated just pc's

**Comment by soydepr** [comment]
here see error 

![image](https://user-images.githubusercontent.com/546367/92607487-32318d80-f282-11ea-96ee-bcea1b8f53e4.png)

**Comment by marcellourbani** [comment]
Ok, looks like you opened the plugin source files, which you only need if you want to contribute.
And you didn't migrate your vscode configuration from the old pc, where you should have an entry like:
```json
  "abapfs.remote": {
    "single_server": {
      "url": "http://my_server:8000",
...
```
