### ISSUE TITLE
Line contains carriage returnabaplint(line_break_style)

### ISSUE THREAD

**Issue by ekekakos** [marcellourbani/vscode_abap_remote_fs#123]
I made the connection following the video instructions in youtube but when I created a new program I get the above error in the 1st line which is a comment (*&----*). How can overcome this?

Thanks

**Comment by larshp** [comment]
This error probably comes from https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint

The rule https://rules.abaplint.org/line_break_style/ is enabled in the default configuration, which I guess you are using?

I'm not sure how to change the configuration when using the remote FS extension

**Comment by ekekakos** [comment]
Yes you are right. Thanks for your help. I raise an issue to this extension in order to get an answer how to overcome.

**Comment by marcellourbani** [comment]
@larshp @ekekakos at the moment there's no way to change abaplint settings for this extension.
I started working on it but have plenty to do to get there

**Comment by larshp** [comment]
any way to default to LF instead of CRLF(carriage return + line feed)? abapGit only works with LF hence the rule in abaplint

**Comment by marcellourbani** [comment]
Don't know.
I pretty much read and write what ADT feeds me unchanged, and have no idea what would happen if I mess with CRs.
My guess is nothing, but might change depending on back end version, and I'm not too keen on finding out.
I don't have time this week, but the next I'll try to sort the abaplint configuration issue.
