### ISSUE TITLE
Display table contents

### ISSUE THREAD

**Issue by marcellourbani** [marcellourbani/vscode_abap_remote_fs#137]
ADT does it for cloud instances

**Comment by uxkjaer** [comment]
These are the API's for showing it on prem

/sap/bc/adt/datapreview/ddic/<tablename>/metadata 
/sap/bc/adt/datapreview/ddic?rowNumber=100&ddicEntityName=<Tablename>

Response:
`<?xml version="1.0" encoding="UTF-8"?>

-<dataPreview:tableData xmlns:dataPreview="http://www.sap.com/adt/dataPreview">

<dataPreview:totalRows>0</dataPreview:totalRows>

<dataPreview:name><TableName></dataPreview:name>

<dataPreview:isHanaAnalyticalView>false</dataPreview:isHanaAnalyticalView>

<dataPreview:queryExecutionTime>1.9530000</dataPreview:queryExecutionTime>


-<dataPreview:columns>

<dataPreview:metadata dataPreview:caseSensitive="false" dataPreview:length="255" dataPreview:isKeyFigure="false" dataPreview:colType="" dataPreview:keyAttribute="false" dataPreview:description="STORY" dataPreview:type="C" dataPreview:name="<Name>"/>


-<dataPreview:dataSet>

<dataPreview:data>hello world 1</dataPreview:data>

</dataPreview:dataSet>

</dataPreview:columns>

</dataPreview:tableData>`

**Comment by marcellourbani** [comment]
Sorry I forgot to close this one.
The Select Query covers this (didn't test on CDS views though, was provided by  @dh4rry )
![image](https://user-images.githubusercontent.com/2453277/110013739-e97efc80-7d19-11eb-901e-5c77bef95a47.png)
