### ISSUE TITLE
Continue: #110136 - TypeError: Cannot read property 'asx:values' of undefined

### ISSUE THREAD

**Issue by i503357** [marcellourbani/vscode_abap_remote_fs#139]
Issue Type: <b>Bug</b>

I am trying to work with VSCode editor for SAP programming. When ever I try to create an object in the added system I am facing this issue. Not sure whether the issue is on VS side or SAP side. Please help me to get rid of this.

Steps to Reproduce:

Add SAP system in VS
Connect to ABAP system using F1 command
Create ABAP FS object
Provide Object Name, description, Package
Getting the error.

Extension version: 0.8.12
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.53GB free)|
|Process Argv|--crash-reporter-id 793617fd-f5a9-4d7a-88b8-ae69a085b727|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by marcellourbani** [comment]
@i503357 sorry for the delay, for some reason I missed this when you created and didn't notice until now
Looks like you're getting an unexpected response, possibly because you're trying to create an unsupported object (by your system I mean) or maybe for some bug.
Could you please give me details about:

- the SAP basis level of your server
- the object you're trying to create: type, name and package

Best regards
Marcello

**Comment by mweinheimer-hb** [comment]
Hey all, 
is there a solution for this topic, i am trying to work with an S/4 system, rather newer than 7.51 and i get the same error when trying to create a simple ABAP report ...

**Comment by marcellourbani** [comment]
I don't think so. What version are you working on? I'll try on the closest I have access to

**Comment by mweinheimer-hb** [comment]
SAP_BASIS 756

**Comment by marcellourbani** [comment]
they probably sunset the folder api. If that's the case it requires a pretty big change

**Comment by mweinheimer-hb** [comment]
Thanks, i am directly in touch with MS and SAP - will stay in touch and keep you updated!
