### ISSUE TITLE
Connect to VS Code error

### ISSUE THREAD

**Issue by jeonghl85** [marcellourbani/vscode_abap_remote_fs#140]
Hi, friend..
First of all, thank you for introducing me to a good experience.

I followed the manual, but I don't think it's connecting well.
(I'll attach an image.)

I'm not sure what the problem is.
I can't get an error message when I connect.

![555](https://user-images.githubusercontent.com/72599551/102637290-bb653400-4190-11eb-8abf-64b2c8cde916.png)

**Comment by jeonghl85** [comment]
> Hi, friend..
> First of all, thank you for introducing me to a good experience.
> 
> I followed the manual, but I don't think it's connecting well.
> (I'll attach an image.)
> 
> I'm not sure what the problem is.
> I can't get an error message when I connect.
> 
> ![555](https://user-images.githubusercontent.com/72599551/102637290-bb653400-4190-11eb-8abf-64b2c8cde916.png)

![666](https://user-images.githubusercontent.com/72599551/102637539-1ac34400-4191-11eb-97af-d8534ed8f13c.png)

**Comment by jeonghl85** [comment]
![666](https://user-images.githubusercontent.com/72599551/102637588-2c0c5080-4191-11eb-86ac-3f1857cae493.png)

**Comment by marcellourbani** [comment]
Hi
Did you try command "AbapFS create connection"  from vscode palette?
Should make it easier to create the right connection.

Other than  that you might have connection issues (i.e. the URL in your config is not reachable, the SICF node is not active, you need single sign on,...)

**Comment by jeonghl85** [comment]
> Hi
> Did you try command "AbapFS create connection" from vscode palette?
> Should make it easier to create the right connection.
> 
> Other than that you might have connection issues (i.e. the URL in your config is not reachable, the SICF node is not active, you need single sign on,...)

After changing it to https url, I connected it and it was successfully.
Thank you.
And I want to ask you one more question.
I created a Hello World program, but I don't know how to run it.. :( 
In eclipse IDE, press F8 to run the program.
but VS code is not lunch that ...haha.
how to run abap program in VS Code? 
^^*

**Comment by marcellourbani** [comment]
Great to read this!
You can't run programs in vscode, but you can:

- run a console application with command 'AbapFs run console application'
- run an unit test with command  'AbapFs run unit test' (Ctrl+Shift+F11)
- open the program in SAPGUI with command 'AbapFs open in SAPGUI' (F5) (and then run it with F8)

Marcello
