### ISSUE TITLE
Changing SAPGUI connection requires restart of vscode

### ISSUE THREAD

**Issue by mbtools** [marcellourbani/vscode_abap_remote_fs#141]
It seems that making changes to the "sapgui" section in settings do not take effect until you restart vscode. If this is correct, then it should be documented or even better the extension should reload the setting without restart.

**Comment by marcellourbani** [comment]
Agreed, it's a bug
I'm a bit wary of changing config on the fly as there's lots of caching going on, but this one is harmless. And is safe for unconnected systems.
