### ISSUE TITLE
Error: The editor does not support enhanced objects (use SAP GUI instead) Won't be able to save changes

### ISSUE THREAD

**Issue by soydepr** [marcellourbani/vscode_abap_remote_fs#143]
What causes this, i cant edit an include ?

**Comment by marcellourbani** [comment]
Hi 
It's a limitation of the ADT APIs, they don't support enhanced includes.
I believe Eclipse has the same limitation, and I can't do much about it

You can edit most other includes, but not that one.

**Comment by soydepr** [comment]
Thank you for your quick response.   
  
  
  
  
  
    
  

  
  
>

**Comment by flaiker** [comment]
Just for reference:

https://blogs.sap.com/2020/04/16/how-dearly-i-would-like-to-edit-my-abap-code-in-my-code-editor-that-is-abap-development-tools-adt-in-eclipsese/
https://answers.sap.com/questions/765841/is-editing-enhancements-with-adteclipse-still-not-.html
