### ISSUE TITLE
"AbapFs Create connection" doesn't accept domain with hyphen

### ISSUE THREAD

**Issue by thedoginthewok** [marcellourbani/vscode_abap_remote_fs#146]
Great work on this project!

When I try to create a connection with the "AbapFs Create connection" command, it does not accept domain names containing hyphens. Manually configuring the same server in the settings.json works fine.

![grafik](https://user-images.githubusercontent.com/6908247/110121507-c4909500-7dbe-11eb-8302-f872058454c6.png)

![grafik](https://user-images.githubusercontent.com/6908247/110121549-cfe3c080-7dbe-11eb-974c-5e2e1f0e4fc7.png)

**Comment by marcellourbani** [comment]
Thanks for the bug report.
Will be fixed in the next release, probably this weekend.

**Comment by marcellourbani** [comment]
I was a bit slower but should be ok now
