### ISSUE TITLE
issue while getting information of transport request

### ISSUE THREAD

**Issue by tute360** [marcellourbani/vscode_abap_remote_fs#148]
I have this configuration in settings:

{
    "workbench.startupEditor": "newUntitledFile",
    "explorer.confirmDragAndDrop": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "explorer.confirmDelete": false,
    "abapfs.remote": {
    
    
        "NPL": {
            "url": "xxxxxx",
            "username": "xxxxxx",
            "password": "xxxxxx",
            "client": "200",
            "language": "ES",
            "allowSelfSigned": true
        }
    }
}

But I'm getting this error while trying to obtain my list of transport request:

"Transport configuration not found"

**Comment by marcellourbani** [comment]
I noticed this a few days ago. Will work after you accessed the transport view from Eclipse at least once.
Will fix this as soon as I have time
