### ISSUE TITLE
invalid lock handle 

### ISSUE THREAD

**Issue by soydepr** [marcellourbani/vscode_abap_remote_fs#149]
we applied sap patches recently and now when saving a program i am getting this error .

is not locked (invalid lock handle: D8520243D16FD78C1FF298A5B50146A50785BC25))

i notice my workespace is untitled  workspace .  i forgot what it should be

**Comment by marcellourbani** [comment]
Hi @soydepr 
I've seen this happening when a file is left open for a long time, if that's the case it should be enough to restart the editor.
If not it will be pretty hard to track without access to a server on the same patch level.

What patches are we talking about?
Is there any chance to give me access to one of your boxes?

Otherwise I'll probably have to ask you to trace calls in Eclipse and send me the logs

**Comment by soydepr** [comment]
Let me install eclipse and get back to you 
Here is exact error 
![5C64A07E-3F9E-4DF9-A5DB-23A71476A302](https://user-images.githubusercontent.com/546367/111833257-4eb12100-88c8-11eb-8336-2bcb1d9dcdca.jpeg)

**Comment by marcellourbani** [comment]
@soydepr what version are you using exactly?
Just realised the upgrade might have deactivated the plugin or make it redundant

**Comment by soydepr** [comment]
we are on release 617 patch 21
  
  
  
    
  

  
  
>

**Comment by marcellourbani** [comment]
Sorry I meant the basis version

**Comment by soydepr** [comment]
SAP_BASIS  740  0024  
  
  
  

  
  
>

**Comment by marcellourbani** [comment]
You need to install this plugin with your version https://github.com/marcellourbani/abapfs_extensions

I guess installing the upgrades disabled it

**Comment by soydepr** [comment]
So you mean I need to remove it and install again   
  
  
  
    
  

  
  
>

**Comment by marcellourbani** [comment]
Not sure, but might work

**Comment by marcellourbani** [comment]
@soydepr any news on this one?

**Comment by soydepr** [comment]
Have to check no longer see adt_srv.    But then how do u still see the programs   
  
  
  
    
  

  
  
>

**Comment by marcellourbani** [comment]
Not sure I understand you

**Comment by marcellourbani** [comment]
Hi @soydepr is this sorted now?
Marcello

**Comment by Gizmich** [comment]
Hello. I have the same issue and also older system (7.40). What if i cant install any plugins on sap system ?

**Comment by marcellourbani** [comment]
@Gizmich I'm not aware of any workaround. Maybe some basis upgrade would fix it, but wouldn't know which one.
we need to do a lock-write-unlock in the same session, and in pre-7.50 systems the session is dropped after lock.
That's why I created the plugin

**Comment by soydepr** [comment]
Sorry delay, was away, no not yet   
  
  
  
    
  

  
  
>

**Comment by Dev4Develop** [comment]
This resolved the issue for me. My SAP  BASIS version was 740 0009

> You need to install this plugin with your version https://github.com/marcellourbani/abapfs_extensions
> 
> I guess installing the upgrades disabled it
