### ISSUE TITLE
Messages from system

### ISSUE THREAD

**Issue by uxkjaer** [marcellourbani/vscode_abap_remote_fs#152]
We could use these API's to get system messages
/sap/bc/adt/runtime/dumps
/sap/bc/adt/runtime/systemmessages

I'm looking into whether it's possible to get an automatic trigger to send via websocket to initiate the API call instead of probing the system.

It's possible to get a nicely formatted message
![image](https://user-images.githubusercontent.com/8186370/113101004-83fe2d00-923f-11eb-89f4-66aca05e0ce6.png)

For info, I found this document, which could prove handy.
https://help.sap.com/doc/2e65ad9a26c84878b1413009f8ac07c3/201909.001/en-US/config_guide_system_backend_abap_development_tools.pdf

**Comment by marcellourbani** [comment]
Hi @uxkjaer 
This would be a nice addition, perhaps could go in the side panel next to transports and abapgit repos:
![image](https://user-images.githubusercontent.com/2453277/113111391-0ff06480-9200-11eb-9259-579efbf93e27.png)

I see eclipse is polling these feeds, so I doon't think we can get a websocket without a custom plugin on the backend

Should be done in 2 steps though:
1) adding the relevant APIs to the [adt library](https://github.com/marcellourbani/abap-adt-api)
    a) GET /sap/bc/adt/feeds (optional,will tell us if the others do exist )
    b) GET /sap/bc/adt/runtime/systemmessages
    c) GET /sap/bc/adt/runtime/dumps
2) integrating them here

**Comment by marcellourbani** [comment]
Actually added this months ago and forgot to close
