### ISSUE TITLE
quickfixes

### ISSUE THREAD

**Issue by uxkjaer** [marcellourbani/vscode_abap_remote_fs#153]
The API /sap/bc/adt/quickfixes handles the Eclipse quickfixes. All is done via post requests.

The following program can be used as a sample with attached postman collection

*&---------------------------------------------------------------------*
*& Report test
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ztest.

WRITE: |Hello WORLD|.

class lcl_test DEFINITION.
PUBLIC SECTION.
methods test.
ENDCLASS.

class lcl_test IMPLEMENTATION.

ENDCLASS.

Remember to change the x-csrf-token
[ADT.postman_collection.json.zip](https://github.com/marcellourbani/vscode_abap_remote_fs/files/6235673/ADT.postman_collection.json.zip)
Quick fix menu response
![image](https://user-images.githubusercontent.com/8186370/113127107-b87fe200-925b-11eb-9da1-aaf41a608146.png)

Actual quickfix response
![image](https://user-images.githubusercontent.com/8186370/113127161-c7669480-925b-11eb-8719-c44d89915e70.png)

**Comment by marcellourbani** [comment]
That's working already:
![fixcode](https://user-images.githubusercontent.com/2453277/113128649-efc9a100-9211-11eb-8a48-999e341ec18b.gif)
