### ISSUE TITLE
abapfs.connect' not found

### ISSUE THREAD

**Issue by samuelmelloul** [marcellourbani/vscode_abap_remote_fs#157]
Hi ,

After installing the plugin and configuring my system i got message: command  'abapfs.connect' not found.
Do you know how to resolve it?
I've already restart VSCODE

Thank you

**Comment by marcellourbani** [comment]
Hi @samuelmelloul that error meanss that the extension was not installed properly.
Did you try uninstalling and reinstalling from the marketplace?
What version of code are you running, and on what OS?

**Comment by samuelmelloul** [comment]
Hi marcello thank you for your answer,

I'm running on OS Windows 10
VSCode version : 1.52.1
For entreprise use i cannot connect directly form the Marketplace. I have downloaded the last version of the extension 0.12.16.
I have already try to uninstall and install many times - doesn't works.

Thank you

**Comment by marcellourbani** [comment]
Did you install all the dependencies?
![image](https://user-images.githubusercontent.com/2453277/119620669-28928a80-bdfd-11eb-8e8c-a7dabc88ea1d.png)

**Comment by samuelmelloul** [comment]
Didn't install winregistry extension.
I'll try it now and let you know 

Thank you

**Comment by samuelmelloul** [comment]
HI Marcello,

I've added all the dependencies.
I've also upgraded to Version 1.56.2 of vscode.
Same error...
Can you please advise

Thank you in advance

**Comment by marcellourbani** [comment]
Do you have an ABAP FS output channel? What does it say?

**Comment by samuelmelloul** [comment]
Sorry for my question, but what is  ABAP FS output channel?

**Comment by marcellourbani** [comment]
![image](https://user-images.githubusercontent.com/2453277/119633029-3f3ede80-be09-11eb-820b-996e00da98c3.png)
Other output channels like extension host or window can give hints about what's wrong.
Without some info from you I have no idea what's the issue here

**Comment by samuelmelloul** [comment]
I have an error under Windows log
[renderer1] [error] net:: ERR_NAME_NOTE_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED
at simpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7029)
at simpleURLLoaderWrapper.emit (events.js:315:20)

**Comment by marcellourbani** [comment]
don't think is relevant. Any on the extension host?
If you want we can set up a remote session to look into it

**Comment by samuelmelloul** [comment]
Nothing in extension host...
I cannot do anything via internet, my office computer has no connection to internet, only local connection

**Comment by marcellourbani** [comment]
Good luck then, I ran out of ideas :(

**Comment by samuelmelloul** [comment]
Thanks anyway

**Comment by ulyssesb** [comment]
The issue appears to be caused by the `winregistry` dependency, as indicated by the error message in the extension host log: `winregistry is not a valid Win32 application`. 

This problem only occurs when running the Arm64 version of VSCode. 
Installing the x64 version solved the issue.

**Comment by marcellourbani** [comment]
I believe I don't need that anymore, will try to fix it at the next release
