### ISSUE TITLE
CSRF token validation failed

### ISSUE THREAD

**Issue by Thymios** [marcellourbani/vscode_abap_remote_fs#158]
Hi,
I am not able to see assigned Transports and System Library assets.
Getting the error "CSRF token validation failed".
VSCode version 1.56
SAP Basis 754

Thanks,
T

**Comment by marcellourbani** [comment]
Hi @Thymios this occasionally happens when a session is expired, opening an abap object or restarting visual studio code should refresh it

**Comment by dcrystalj** [comment]
what does it mean to "opening an abap object " I tried to close and open file but cannot make any changes. Restarting vscode everytime after computer goes to sleeps seems wrong
