### ISSUE TITLE
older versions of sapa 

### ISSUE THREAD

**Issue by siasty** [marcellourbani/vscode_abap_remote_fs#159]
hi, i wonder if it is possible to connect to older sap versions like 4.5b ? maybe you would like to develop the tool for older versions?

**Comment by marcellourbani** [comment]
Afraid not
I'm using the adt plugin Eclipse uses, so the short version is that can only work for versions who support eclipse

**Comment by siasty** [comment]
Hi, I'm back with the topic of integration after rfc ... I have a problem with vscode. You wrote a great tool, maybe you have encountered such a problem...
when I script the simple node-rfc code it works fine... but when i run code  i have error "The SAP NW RFC SDK could not be loaded, check the installation "  already when importing the library ..

"const noderfc = require("node-rfc");"

do you have any idea what is wrong? I'm out of ideas :(
![Przechwytywanie](https://user-images.githubusercontent.com/39690589/165088025-d01a59b3-a5d2-42a6-a97d-c86c0ceaae4d.JPG)
