### ISSUE TITLE
could not connect to localhost:8000 if I am using the SAP Developer Express edition in local container

### ISSUE THREAD

**Issue by davidchencloudexceed** [marcellourbani/vscode_abap_remote_fs#160]
Hello,
I am using the container provided by SAP and run it in my local Win10 desktop.
https://hub.docker.com/_/sap-abap-trial/plans/ac8a4f9b-ae29-4afa-9b39-25aeea24b821?tab=instructions
Below are the port used by the container

3200: SAPGUI Instance 00
3300: RFC Instance 00
8443: SAP Cloud Connector
30213: SAP HANA MDC Database
50000: AS ABAP HTTP
50001: AS ABAP HTTPS

I can use SAPGui and Eclipse ABAP plugin to connect to my container. But when I use the fs, the deafult url is localhost:8000.
I am not sure what's the right connection port fs using.

the error I got from VSCode is "Failed to connect to abapConnection1:Error: socket hang up"

Thx,
David

**Comment by marcellourbani** [comment]
Hi @davidchencloudexceed I believe you need to enable /sap/bc/adt in transaction SICF
Might need a couple more for help and other things

Regards
Marcello

**Comment by davidchencloudexceed** [comment]
@marcellourbani  I think my container just runs fine. I can use SAPGui and also Eclipse to connect successfully.  Is remote_fs using a different port than SAPGui?

**Comment by marcellourbani** [comment]
Yes, different port and different technique.
You need to enable that node
