### ISSUE TITLE
Error when trying to open/edit Classes

### ISSUE THREAD

**Issue by just-maik** [marcellourbani/vscode_abap_remote_fs#161]
Hello. I'm a pretty new ABAP developer and trying my best to use the SAPGUI as least as possible.
Since we are doing a lot of backend for webapps with SAP, I wanted to edit a Class.
When I try to open it through the Search function or via the File Explorer, I get the following error on all Classes I've try'd to open so far.

```
Error in stat of adt://tst/System%20Library/****/Quellbibliothek/Klassen/ZCL_NAD_BIBLIOTHEK_SHOP
TypeError: Cannot read property 'href' of undefined
```

Klassen = Class, sorry for the German language setting.
Almost seems to me as if it try's to open the Class as a directory when truly its just a .abap file

**Comment by marcellourbani** [comment]
Hi @just-maik 
I didn't test much in non-english languages but should work.
There are known issues for local objects owned by others, objects with repairs or enhancements and a few bugs in SAP APIs.
Please try:

1. close vscode
2. open it again
3. search for ZCL_NAD_BIBLIOTHEK_SHOP
4. if this doesn't work, try Eclipse. If that doesn't open an OSS note :(

Anyway this will not replace SE80 completely.
