### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by BrunoKrugel** [marcellourbani/vscode_abap_remote_fs#164]
Hello,

I configured a connection to my ABAP system, but when I try to connect I receive the error :

`Failed to connect to SYS:Error: read ECONNRESET`

The system configuration:

```
        "SYS": {
            "name": "ER9",
            "url": "http://myurl:4554",
            "username": "xxx",
            "password": "yyy",
            "language": "en",
            "client": "001",
            "allowSelfSigned": true,
            "diff_formatter": "ADT formatter"
        }
```

**Comment by larshp** [comment]
in the name, SAP systems is usually 3 characters? `"name": "ER90",`

**Comment by marcellourbani** [comment]
I don't think there's a name field in the configuration. Removing it sounds like a good idea but doubt will fix it.
that error looks like some network/firewall issue, hard to tell if there's more.
Please check the ABAPFS and extension host messages to see if there's some debug info there

**Comment by BrunoKrugel** [comment]
I used the AbapFS Create connection and asked for a name and included the field in the configuration.
> Please check the ABAPFS and extension host messages to see if there's some debug info there
How can I do that?

**Comment by larshp** [comment]
check the lower part of the screenshot in https://github.com/marcellourbani/vscode_abap_remote_fs/issues/163

**Comment by kdbeall** [comment]
@larshp @marcellourbani I am also receiving this error.

**Comment by marcellourbani** [comment]
@kdbeall 
what happens if you open with a browser

 http://<yourserver>:<yourport>/sap/bc/adt/functions/groups/sfunction_builder/source/main

The plugin requires that URL to be accessible

**Comment by BrunoKrugel** [comment]
![image](https://user-images.githubusercontent.com/30608179/125957185-de434f39-381a-4065-894d-4503a06d9ef4.png)
This is the only output that I have in the log when I try to connect.

> http://:/sap/bc/adt/functions/groups/sfunction_builder/source/main
If I try to access this link I receive a ERR_NAME_NOT_RESOLVED

**Comment by marcellourbani** [comment]
@BrunoKrugel you need the server and port in that url too. Sorry, I didn't realise github hid my \<yourserver\> as sees it as a markdown tag. Fixed now

About the logs, it's mostly about the ABAP FS ones, you can switch log channel with a dropdown
![image](https://user-images.githubusercontent.com/2453277/125979605-9892e981-ae3c-4aa0-b86c-e51a0d636565.png)

**Comment by kdbeall** [comment]
Figured it out! It was an installation issue on my side.

**Comment by marcellourbani** [comment]
@kdbeall great to read it! Out of curiosity,  what was the issue?

**Comment by kdbeall** [comment]
@marcellourbani I wish I wrote a faster response! I have been on vacation. I am not entirely sure. My educated guess is that something wasn't running. I realized I had to run the command `sapcontrol -nr 00 -function GetProcessList` to check everything was up and running.

**Comment by marcellourbani** [comment]
No worries. It's hobby work anyway ;-)
Thanks for the reply,!
