### ISSUE TITLE
editor.document.save always returns true in command activate

### ISSUE THREAD

**Issue by uxkjaer** [marcellourbani/vscode_abap_remote_fs#166]
The save step in the activate function always returns true.

If you edit a file and press activate and quickly type something immediately after, then the error comes up, the exception that is raised is caught somewhere and not raised to the command.ts file.

![image](https://user-images.githubusercontent.com/8186370/127866029-afac9118-5cfd-4c22-a594-22c958d3760a.png)

**Comment by uxkjaer** [comment]
i do experience another issue where after clicking the activate and it does the save. Then after activate it it returns back to the "old" source. It seems to stuff up in SE24 as well. See https://im7.ezgif.com/tmp/ezgif-7-d628d733f1e8.gif
I need to do another edit in SE24 to return back to "normal" state. Not sure this is a bug in ADT or how it's called from VSCode. I see that after the save, in Eclipse it does a get for inactive version, then an unlock before it requests the activation
![image](https://user-images.githubusercontent.com/8186370/128980579-439aac56-af9c-4488-9e06-2b36fb66a3b0.png)

**Comment by marcellourbani** [comment]
Never seen this. Are you maybe able to reproduce publicly (i.e. git repo or sharable code, hopefully for the trial image)?

**Comment by marcellourbani** [comment]
@uxkjaer now that I look better, when you have a syntax error like that the class is never saved.
You can save one with syntax errors, but with this one the file abstraction falls apart and the backend is not able to separate it in methoids and declarations, so have no place to save it to
