### ISSUE TITLE
How to run a report ?

### ISSUE THREAD

**Issue by sh4rp0** [marcellourbani/vscode_abap_remote_fs#167]
Can someone explain me how to acutally run a report and what has to be set-up first? 

I get this error, when trying to run the code.
![image](https://user-images.githubusercontent.com/81947603/134629120-4e643379-8713-488a-8cb5-c4e2505b2974.png)

I was still pressing run without debugging, then I tried the debugging optin which did create a workspace.json 

What has to be configured here?

**Comment by marcellourbani** [comment]
Hi @sh4rp0 sadly running reports is not supported yet.
Debug works for unit tests, RFC and web calls
I think you also bumped against some bug in the windows debugging code.
Did you ever run the eclipse or the spgui debugger?
Also, you might find some logs in the ABAP FS output channel in code
