### ISSUE TITLE
Command 'abapfs.connect' not found

### ISSUE THREAD

**Issue by MLogan1998** [marcellourbani/vscode_abap_remote_fs#173]
After installation of the extension and configuration I am unable to run. 

Error: "Command 'AbapFs Connect to and ABAP system' resulted in an error (command 'abapfs.connect' not found)

I have restarted VSC. 

I'm wondering if something went wrong with my installation. Had to download extension from browser and install from VSIX  because of proxy issues.

**Comment by marcellourbani** [comment]
Hi
Did you install the dependencies?
Won't activate without them

**Comment by FeiMinhao** [comment]
Hello @MLogan1998 ,
may I ask how did you fix the issue "AbapFs Connect to and ABAP system". I'm facing the same issue. I have install the extension successfully in my vscode.

**Comment by FeiMinhao** [comment]
Hi @marcellourbani,

I have changed back to the old version 1.09. It works now. Seems something wrong in the current new version.
With the current new version I got only one message in Output and no more further progress:
"activating ABAPfs..."
