### ISSUE TITLE
403 error for BTP ABAP connection

### ISSUE THREAD

**Issue by phanikumarps** [marcellourbani/vscode_abap_remote_fs#174]
Is it possible to use this for BTP ABAP instance? I am receiving 403 error w/ following settings:
![2021-12-29_11-45-23](https://user-images.githubusercontent.com/87087924/147698109-4c132f95-9307-49b4-a9ea-82998dded4e2.png)

403 error:
![403-error](https://user-images.githubusercontent.com/87087924/147698146-b51697d7-8095-4c89-b5ec-2aa83975eead.png)

**Comment by phanikumarps** [comment]
This got resolved after making sure:
url points to BTP instance endpoint &
loginUrl points to ABAP instance endpoint.

I am now able connect.

**Comment by marcellourbani** [comment]
Great to read that!
Out of curiosity, did you generate your connection with the wizard or manually?

Regards
Marcello

**Comment by phanikumarps** [comment]
Manual, not through wizard.
