### ISSUE TITLE
Add support for secure network communication

### ISSUE THREAD

**Issue by pietbrauer** [marcellourbani/vscode_abap_remote_fs#175]
Some of our SAP instances are must use secure network communication and I wasn't able to find a setting for it using this plugin.

I was able to get the communication working using Eclipse, so I guess it's possible without SAPGUI, but would love to use VSCode for development.

Any pointers are welcome and I am happy to submit a PR.

**Comment by marcellourbani** [comment]
@pietbrauer this plugin works over http(s), eclipse over RFC.
secure communication is supported over https

See the [wiki](https://github.com/marcellourbani/vscode_abap_remote_fs/wiki/installation)

**Comment by pietbrauer** [comment]
Yes, I uses https but it doesn't start the Secure Login Client?

**Comment by marcellourbani** [comment]
No idea what you're talking about: maybe some sort of single sign on?
For SSO this only supports oauth bearer tokens, and I only ever tried it with my SAP cloud trial account

**Comment by flaiker** [comment]
I think it's this?

![image](https://user-images.githubusercontent.com/5270359/154554762-311a6817-3a8f-4c86-a169-4be065ab751f.png)

**Comment by marcellourbani** [comment]
yep that applies to RFC connections, used by Eclipse and sapgui. This plugin goes over HTTP(S) and just doesn't have that setting

**Comment by pietbrauer** [comment]
I understand that. So it should just work over HTTPS? I thought the server enforcing this “ultra secure connection” is the reason I am unable to connect to the servers.

**Comment by marcellourbani** [comment]
Hard to say where the problem is without access to your system.
If you can access fiori applications with the same base URL without using a proxy you should be fine
Also you'll need to activate the SICF node
