### ISSUE TITLE
Failed to save 'xxx' unable to write file

### ISSUE THREAD

**Issue by pepealbuixech** [marcellourbani/vscode_abap_remote_fs#176]
When I try to save something, the editor shows me the following error:
_Failed to save 'ZCL_KIT_ALM.clas.abap': Unable to write file 'adt://xx/System Library/xx/Source Code Library/Clases/ZCL_KIT_ALM/ZCL_KIT_ALM.clas.abap' (Error: Unknown transport status. Object not locked?)_

There's something I missed in the installation?

The transport order looks like:
![image](https://user-images.githubusercontent.com/12658019/153385539-044aa2d5-0055-47c9-982c-adff3196db65.png)

Thank you!
Pepe

**Comment by pepealbuixech** [comment]
Hi Marcello, 
thanks for the response time, yes our version is the 7.50, I'll try to install the abapGit plugin and test it again.
Best Regards,
Pepe

**Comment by duizhang8255** [comment]
Hello Pepe,

Did you issue have been fixed?
I also install abapGit in backend system, but still have this issue, my system version is 7.50.

Thanks.

Best regards,
Martin

**Comment by marcellourbani** [comment]
After abapgit you need to install the plugin mentioned in the Readme

**Comment by pepealbuixech** [comment]
Hi Martin, my SAP admin didn't allow me to install it :(

**Comment by THouRxx** [comment]
> Hello Pepe,
> 
> Did you issue have been fixed? I also install abapGit in backend system, but still have this issue, my system version is 7.50.
> 
> Thanks.
> 
> Best regards, Martin

@duizhang8255 

I have the same problem for 7.50. Have you found a solution? 
We're also going to update ur system to a newer version anyways. So maybe that's working.

**Comment by marcellourbani** [comment]
@pepealbuixech 
You probably need to install this on your ABAP system: https://github.com/marcellourbani/abapfs_extensions

**Comment by THouRxx** [comment]
@marcellourbani 

I did. But unfortunately it still brings up this error

> Failed to save 'ZCL_KIT_ALM.clas.abap': Unable to write file 'adt://xx/System Library/xx/Source Code Library/Clases/ZCL_KIT_ALM/ZCL_KIT_ALM.clas.abap' (Error: Unknown transport status. Object not locked?)

**Comment by marcellourbani** [comment]
Strange, should propose you to pick or create a transport
Does that happen even if you already have an open transpot for the object being edited?

For the 2nd error could be a known bug: doesn't support local objects not owned by you or without package assignment

**Comment by THouRxx** [comment]
@marcellourbani 

This happend on my own open transport. The objects are stored in a package.
In this case I used a package from the repository that does not run on abapgit.

Can I only edit packages that are linked to abapgit? (due to the older SAP version)

**Comment by marcellourbani** [comment]
no, abapgit shouldn't matter
No idea why it's not working for you, I tested this with both newer and
older systems than yours, and have a few thousand users (my own estimate,
from 16k downloads). Would need access to your system to investigate further

**Comment by THouRxx** [comment]
We will upgrade to a newer version later this year. Then I will try again and give feedback. Thanks for now. Appreciate your work.
