### ISSUE TITLE
Connecting to BTP ABAP Environment

### ISSUE THREAD

**Issue by tcjgec2008** [marcellourbani/vscode_abap_remote_fs#177]
Hi ,

I am trying to connect to BTP ABAP environment using: 
1. ABAP FS Create Connection -> Cloud Instance. Enter connection End Point ( https://api.cf.eu10.hana.ondemand.com ) -> User Name and Password -> Specify the existing Service Key SAP_ADT. 
2. Post the previous step it successfully authenticates in a separate browser.
3. Asks for destination File: User or workspace. 
4. Selecting any one option. Asks for Connection Name ->Save Credentials-> Pops for Language.. Post that nothing loads up.
Any idea on this. Any specific config that is missing.

Thanks
Tirthankar

**Comment by mubasis** [comment]
Hi @tcjgec2008 
All looks good
You should now have the ABAP system in tour workspace
![image](https://user-images.githubusercontent.com/103058064/161813056-e38342d3-bc21-48be-8380-7dedd194fb5a.png)

You can navigate to your object or search for it with command abapfs search

![image](https://user-images.githubusercontent.com/103058064/161813289-d8ae856f-a56b-4370-8b58-1dba6f598fc4.png)

![image](https://user-images.githubusercontent.com/103058064/161813397-fb73303f-fae6-45e8-b617-8948567b0f14.png)

**Comment by tcjgec2008** [comment]
Hi @marcellourbani ,

Thanks for your reply.Searching ABAP Objects gives me an error as below:
"No ABAP File System mounted in Workspace".
Also, There is not any project created under the Explorer of the VS Code.
Any idea on this.

Thanks
Tirthankar

**Comment by marcellourbani** [comment]
@tcjgec2008 
Did you connect to the system?
The steps you listed above create a connection in your config files, but then you need to run the abapfs connect command to connect

**Comment by tcjgec2008** [comment]
Hi @marcellourbani ,
Super. Thats the step , it was missing for me. 👍 👍 
1 quick info:
We raised with SAP and 1 basic error we are getting is connecting to Onpremise Gitlab Server from BTP ABAP.
SAP has confirmed that for utilising abapgit, Gitserver should be available over the internet.
Does Vscode based GIT overcomes this obstacle.
Any idea on this.
Anyways many thanks for that help for connecting to the vscode from ABAP BTP. 👍 

Thanks
Tirthankar

**Comment by marcellourbani** [comment]
Hi @tcjgec2008 
The integrated abapgit is based on SAP's, so it won't work

You can probably work around it with localtunnel or ngrok, but your IT won't like it :) 

You can access gitlab from your laptop on vscode but it's not the same

**Comment by marcellourbani** [comment]
PS: better than localtunnel, you can create your own private mirror on github and sync it via laptop
But it's off topic
