### ISSUE TITLE
When save a change, a sap gui window opens with the object

### ISSUE THREAD

**Issue by norman003** [marcellourbani/vscode_abap_remote_fs#178]
SAPLOGON 7.7 patch 6
SAP_BASIS 750
ZABAPGIT Installed

**Comment by marcellourbani** [comment]
Can you please give mesome more information? What object?
can you send a screenshot?

**Comment by norman003** [comment]
Save a program, automatically a sap gui window open and run
![image](https://user-images.githubusercontent.com/33376952/162579832-d6740e0b-f862-491c-842e-2d7ce05a4c83.png)
![image](https://user-images.githubusercontent.com/33376952/162579860-a2f60570-13c2-4c59-8ab8-b3cf7b587a41.png)

Save a include, automatically a sap gui window open mode edit
![image](https://user-images.githubusercontent.com/33376952/162579948-4514404c-28b5-46c8-bc0d-43c58b14562c.png)
![image](https://user-images.githubusercontent.com/33376952/162579971-6a8342f9-87e0-478b-8ae4-834de3dbd5d7.png)

**Comment by marcellourbani** [comment]
Looks like you assigned ctrl+s to the command "AbapFs Show in GUI" (abapfs.execute)
Saving with the menu should work, but I recommend you remove the key binding

**Comment by norman003** [comment]
Sorry and thanks, if that was it.
