### ISSUE TITLE
Failed to connect to SYS:Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by AlexanderK22** [marcellourbani/vscode_abap_remote_fs#180]
I'm trying to connect to our SAP system but when I do I get the error:
```Failed to connect to SYS:Cannot set headers after they are sent to the client```.

I assume this is related to being behind a corporate proxy with a self signed certificate.

**Comment by marcellourbani** [comment]
Hi Alexander
That's probably true, this doesn't really support proxies

Will try to fix it

Regards
Marcello

**Comment by dsdaraujo** [comment]
Hello guys, 
I have also been struggling with this issue for a while, and have just found out how to fix it. 
You have to change VSCode settings, setting Proxy Support to "off" (see below).
Afterwards, configure "http_proxy" and "https_proxy" environment variables for your user (all lower case) with the url, port, username and password for the proxy (http://username:password@url:port). 
Important: https_proxy has also url with HTTP, and not HTTPS. 
Also, environment variable "no_proxy", to bypass proxy for local domains (localhost,127.0.0.1,*.yourdomain.com).
![image](https://user-images.githubusercontent.com/65226/228494297-61dddadd-11e5-4268-b733-511f830f9e7f.png)
![image](https://user-images.githubusercontent.com/65226/228495479-1e3a7576-7316-4cd9-ae76-ef6c7a105571.png)

**Comment by marcellourbani** [comment]
Thanks for this!
I should really look into it

**Comment by lhemkendreis** [comment]
I would love to find a solution to this! 

My SAP System is behind a Proxy and when I try to connect, get this Error:
`Failed to connect to E31:AxiosError: Request failed with status code 403`

When I set the proxy url (including my login details), as the "HTTP: Proxy" setting in VSCode, then I get the error mentioned by @AlexanderK22: 
`Failed to connect to SYS:Cannot set headers after they are sent to the client.`

I tried to use the solution mentioned by @dsdaraujo, but it did not work for me. I just went back to Error 403.

**Comment by marcellourbani** [comment]
@dsdaraujo @lhemkendreis 
I was about to code it tonight when I found out it's built in vscode!
@AlexanderK22  this might fix your issue too perhaps with http.proxyAuthorization, or maybe not...

This will go in the README at next commit  :

## Proxy support

There's no direct support for proxies in the application, but you can use the builtin proxy in vscode, just use the option 'Use the proxy support for extensions.' If you only want to do it for a single system you can do it in its workspace (and save it, which is a good idea anyway)

![image](https://user-images.githubusercontent.com/2453277/228667375-2c0d189e-3e08-4cbe-8307-721a7d4454f8.png)


```json
{
  "http.proxySupport": "on",
  "http.proxy": "http://localhost:3128"
}
```
