### ISSUE TITLE
Cannot open FMs, message content not acceptable

### ISSUE THREAD

**Issue by ToffeeNeko** [marcellourbani/vscode_abap_remote_fs#181]
In short when trying to open or create an SE37 object (function group, function module, etc.), like clicking on the name of function group below:

![image](https://user-images.githubusercontent.com/53738915/180861455-9791d0e3-0b64-448e-bf5a-8538b3d4c54c.png)

Then the following error message will popup:

`The message content is not acceptable. Accepted content types: application/vnd.sap.as+xml`

![image](https://user-images.githubusercontent.com/53738915/180860690-485f4759-3117-46d3-8378-27c3528c8e65.png)

The result is no se37 object can be viewed, even using abapfs:search for an existing FM, will still get the same error when trying to open the code. However opening SE38 programs and SE24 classes will not trigger this error.

The error didn't happen until a week ago, when my PC suddenly lost internet connection when using abapfs to open a function module. Reinstalling the extension doesn't help. 😥

**Comment by marcellourbani** [comment]
I recently introduced a bug like this and fixed it like yesterday
Please try to update the plugin
If that doesn't work, downgrading to a version from al least a month ago should
Please let me know if upgrade does not work though

**Comment by ToffeeNeko** [comment]
Much thanks for your rapid reply! The most recent version 1.4.9 still has this bug. After downgrading to an older version the bug disappears.

![image](https://user-images.githubusercontent.com/53738915/180869200-88d38a42-6ddb-4871-881b-827dbe30ec6b.png)

**Comment by marcellourbani** [comment]
I just published 1.4.10 which should revert the offending code (which was supposed to fix a much rarer edge case)
Could you please check if that works for you?

**Comment by ToffeeNeko** [comment]
Yep 1.4.10 no longer has this problem. That's so efficient haha.
