### ISSUE TITLE
Unable to open registry key when run debug

### ISSUE THREAD

**Issue by ToffeeNeko** [marcellourbani/vscode_abap_remote_fs#182]
Here's another unrelated problem that has been happening to me for long. 😥 (not due to the latest update)

When trying to debug and run (F5) an abap object, vocode will popup this error message:

![image](https://user-images.githubusercontent.com/53738915/181042395-73d7d95c-0e7b-4b28-8253-765c06288549.png)

It may be caused by some local settings but I cannot figure it out. Any idea on this problem?

**Comment by marcellourbani** [comment]
No idea, works for me. Even under windows :P

**Comment by marcellourbani** [comment]
did you try creating a launch.json?

**Comment by ToffeeNeko** [comment]
Just tried another laptop but sadly the error remains😥

**Comment by marcellourbani** [comment]
Works on mine. Are you an administrator or your laptop?

**Comment by marcellourbani** [comment]
I do think it reads the registry for the ideid and terminal id. Might have to change that

**Comment by marcellourbani** [comment]
@ToffeeNeko I suspect for now it only works if you tried debugging once in eclipse.
I'll fix it

**Comment by ToffeeNeko** [comment]
Yep I have admin right on both laptops and even started vscode in admin mode, and never installed eclipse on them. Waiting for you good news! 😂

**Comment by marcellourbani** [comment]
@ToffeeNeko can you please try importing this as a .reg file?

terminalId.reg
```
[HKEY_CURRENT_USER\SOFTWARE\SAP\ABAP Debugging]
"TerminalID"="D5FD3ED0E1D311EDB5EA0242AC120002"
```

**Comment by ToffeeNeko** [comment]
@marcellourbani Much appreciated, it works! While pressing ctrl+shift+f11 I was directed to testing panel and there's no tests configured. Could you please show me some hints on how to debug run a function module with certain input variables? Like what we usually do in GUI debugger. 

![image](https://user-images.githubusercontent.com/53738915/234075308-6f929b16-3c06-41cc-9813-ff3740511b71.png)

**Comment by marcellourbani** [comment]
re's no FM testing facility, so you can pick one of the following options:

- call the FM over RFC
- create an unit test class

sadly SAPGUI debugging is not supported(couldn't figure out how to drive the GUI )

**Comment by ToffeeNeko** [comment]
🤔Sorry but got a bit confused... Let's say, now I have an RFC ZRFC1.fugr.abap opened in vscode and a breakpoint is also set in vscode; Then press F5 jump to debug page and attach to server, now how should I call this RFC so that it can stop at the breakpoint and show variables in vscode? 

I tried to open this RFC in GUI using the same user and call it, but apparently it didn't stop. Do I need to configure things like user and external breakpoint in GUI before calling?

**Comment by marcellourbani** [comment]
Example:
![image](https://user-images.githubusercontent.com/2453277/234121894-195b7717-8ec5-44a4-88c0-16f79637b9e6.png)
![Screenshot_20230424_223634](https://user-images.githubusercontent.com/2453277/234122195-139451e9-6aec-476f-a496-abf6dabcec78.png)

**Comment by ToffeeNeko** [comment]
Perfect! Finally make it work! That's so kind of you! 🥰

**Comment by marcellourbani** [comment]
Sorry it took so long

**Comment by ToffeeNeko** [comment]
No problem haha, you are much appreciated!
