### ISSUE TITLE
After modification, it does not take effect in GUI.

### ISSUE THREAD

**Issue by fun-li** [marcellourbani/vscode_abap_remote_fs#184]
**Translated by Google, so it may be difficult to understand**

I edited the code and saved it with Ctrl+S, but I did not see the change in the gui.
![image](https://user-images.githubusercontent.com/57790422/184586678-a38780b6-0098-42d7-b71a-fc428c37d3da.png)

![image](https://user-images.githubusercontent.com/57790422/184587054-e1162a6f-1fe0-4129-8c0c-dd0d3e7f0547.png)

Finally I found the code change in version management, the status is inactive, but the code cannot be activated via GUI at this time

![image](https://user-images.githubusercontent.com/57790422/184587231-f7e2315f-c5c7-4382-bfdd-027065d4c5e8.png)

After closing the editing window of VScode and reopening it, the code modification is lost.

![image](https://user-images.githubusercontent.com/57790422/184587419-11a6b290-3e4b-45c1-b61d-4e8689cd23fb.png)

**Comment by marcellourbani** [comment]
Hi @fun-li 
The most common cause of this is missing functionality in the ABAP server.
from README:

> Unless your system is very modern (7.51 or later I think), write support will require you to install [this plugin](https://github.com/marcellourbani/abapfs_extensions) in your dev server to enable. Browsing works even without it

**Comment by fun-li** [comment]
@marcellourbani 
Thank you for your quick reply.This is the version information of our SAP， Do I still need to install  `abapfs_extensions` ？

**Comment by fun-li** [comment]
@marcellourbani 
![image](https://user-images.githubusercontent.com/57790422/184594290-da3bda97-4c63-479c-ae36-379bedef21f3.png)

**Comment by marcellourbani** [comment]
I meant the basis level, however looks pretty modern and should be supported.
Sadly I have no idea, as I don't have access to a similar system

**Comment by fun-li** [comment]
@marcellourbani  I have solved this problem by installing abapfs_extensions. Thanks.
