### ISSUE TITLE
How to use vscode abap remote fs with Single sign-on

### ISSUE THREAD

**Issue by voidsteed** [marcellourbani/vscode_abap_remote_fs#186]
Hi,

My organization is using SSO and activate Secure Netowrk Communication and a list SAP servers showed up in my SAPGUI automatically. How do I use 
vscode_abap_remote_fs with this kind of server?

And I know Eclipse uses RFCs, and here is my setting in Eclipse:
![remoteserverquestion](https://user-images.githubusercontent.com/2634606/202354189-43f85f17-fc64-4bcb-9f34-9fcf945c961c.png)

Thank you!

**Comment by marcellourbani** [comment]
Hi
Sadly this goes over HTTPS, not RFC
The base url of your fiori apps should work, but the only sdo supported is
OAUTH2 tokens, I only tested it with btp instances
Marcello

**Comment by marcellourbani** [comment]
Actually, now that I think about, in Issue #185 @andwehrm proposed a [workaround](https://github.com/andwehrm/rfc-connector)

**Comment by voidsteed** [comment]
Thanks, @marcellourbani. I will take a look and try it out
