### ISSUE TITLE
External breakpoints

### ISSUE THREAD

**Issue by maggiv8** [marcellourbani/vscode_abap_remote_fs#190]
Hi there,

is there any way to set external breakpoints? It would come in very handy when testing ABAP code incorporated in a SAP Standard business process (e.g. when implementing a BAdI).

Thank you.
Kind regards
Christoph

**Comment by marcellourbani** [comment]
Pretty easy, just click on the left of the code and start the debugger with F5. See [here](https://blogs.sap.com/2021/04/21/debugging-abap-in-visual-studio-code/).
No sapgui debugging though, only RFC/HTTP/abap unit

**Comment by maggiv8** [comment]
Hi Marcello,

thank you for your quick response. 
Overall, the plugin is really impressive.
The challenge and question I am having is: I am triggering a process out of SAP GUI or a web service (e.g. to create an account). This process (e.g. account creation) invokes a BAdI implementation. The process is executed with my user, but obviously not out of VS Studio. In SAPGUI I can set an external breakpoint for this user, so whenever this user invokes the BAdI implementation via the execution of this particular process, the system stops at the external breakpoint for this user.
I am unusre how to do this with your plugin.

Thank you for your help.
Kind regards
Christoph

**Comment by marcellourbani** [comment]
It's not supported
That requires controlling the sapgui and I'm not quite sure how.

If you call it over rfc/http or an unit test triggered in the plugin it
does, but no sapgui
