### ISSUE TITLE
If i re-save or activate after the first activation of the abap source in vscode, there is no response

### ISSUE THREAD

**Issue by bbongtree** [marcellourbani/vscode_abap_remote_fs#191]
If i re-save or activate after the first activation of the abap source in vscode, there is no response

But the abap trial version works well

not work sap s4hana 2021 fps02 version

Also, if i run the vscode app again after the vscode app is exited, it will work well

**Comment by marcellourbani** [comment]
Hello
I'm not sure I understand exactly what you mean.
I did get some quirky saving behaviour in a 7.52 system, while works fine on both older and newer systems in my organization and the cloud trial. hard to tell what's your specific issue without access to your system (mine seems to be an API bug btw)

**Comment by bbongtree** [comment]
Hello 

im record this screen

https://drive.google.com/file/d/1B7jEh_2M0zfXJRAvzEzwfY92WBxRSh7u/view

**Comment by marcellourbani** [comment]
Thank you
Yes, it's a valid bug, and happens on my 5.2 system too. Fought quite a bit to try and fix it, but failed.
I believe it's linked to a bug in ADT backend, but I think Eclipse is way less sensitive to it
Sorry but I have no idea how to fix it

Marcello

**Comment by bbongtree** [comment]
Hello bro!!

Thank you

But cds view works well. I guess it's a bug

**Comment by bbongtree** [comment]
Hello bro

I temporarily solved it on the ADT backend for now

I don't know if it's the right way, but it works

![Screenshot_20230627_091343_Remote Desktop](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/132864924/8fcc8d9a-2f96-4633-92e0-c78c6ccbb117)

**Comment by marcellourbani** [comment]
Good to read that.
Afrait you'll ruin your where used list though
Marcello

**Comment by bbongtree** [comment]
I've been using it for 2 days now and I'm satisfied that it's being activated very well

**Comment by marcellourbani** [comment]
Latest release should fix this. Please reopen if not
