### ISSUE TITLE
Can connect but don't see any workspace

### ISSUE THREAD

**Issue by dcrystalj** [marcellourbani/vscode_abap_remote_fs#194]
My config:
```
    "abapfs.remote": {
        "tst": {
            "url": "http://sapdev.server.local:8000",
            "username": "MYUSERNAME",
            "password":  "some...!",
            "language": "EN",
            "client": "200",
            "allowSelfSigned": true
        }
    },
```
Vscode output is this
```
activating ABAPfs...
creating language client...
starting language client...
Activated,pid=74700, activation time(ms):5
Error in stat of adt://tst/pom.xml
adt://tst/pom.xml
Error in stat of adt://tst/build.gradle
adt://tst/build.gradle
Error in stat of adt://tst/pyproject.toml
adt://tst/pyproject.toml
Error in stat of adt://tst/setup.cfg
adt://tst/setup.cfg
Error in stat of adt://tst/tox.ini
adt://tst/tox.ini
Error in stat of adt://tst/pylintrc
adt://tst/pylintrc
Error in stat of adt://tst/node_modules
adt://tst/node_modules
Error in stat of adt://tst/pom.xml
adt://tst/pom.xml
Error in stat of adt://tst/app/src/main/AndroidManifest.xml
adt://tst/app/src/main/AndroidManifest.xml
...
```

**Comment by dcrystalj** [comment]
Workspace was not under extension tab but in files 😓

**Comment by maggiv8** [comment]
Hi there,

could you please let me know how exactly you solved this issue as I am having the exact same problem. Unfortunately your comment about 'workplace was not under extension' is not a 100% clear to me.

Thank you.
Kind regards
Christoph

**Comment by maggiv8** [comment]
> Workspace was not under extension tab but in files

Hi there,

could you please let me know how exactly you solved this issue as I am having the exact same problem. Unfortunately your comment about 'workplace was not under extension' is not a 100% clear to me.

Thank you.
Kind regards
Christoph

**Comment by dcrystalj** [comment]
No need to open "abap fs" in sidebar. You will see remote files under "explorer" sidebar after restart. 
However due to a lot of locking problems with files this extension was unusable to me. Had to switch to eclipse 👎

**Comment by marcellourbani** [comment]
Sorry to read that

**Comment by dcrystalj** [comment]
If you know any solution, you are welcome. Vscode keeps reverting my changes on save. while no error is output to abap fs console. I believe this is some locking issues :|

**Comment by marcellourbani** [comment]
Ok, that's another story.
This si the highest priority bug right now, and affects one of my dev systems too.
Worked quite a bit on it but couldn't find a way to fix yet
