### ISSUE TITLE
Object not found in workspace

### ISSUE THREAD

**Issue by norman003** [marcellourbani/vscode_abap_remote_fs#195]
It happened to someone that I found the object
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/33376952/de60317e-cf06-41cd-bff1-d2915a1b2681)

but can't open it
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/33376952/c9a66fb5-9ac5-4ac4-af64-d86ea41d239b)

**Comment by Dimifistifaied** [comment]
Hello, 

I observe the same pattern. Via the VS extension I can create a new package in $TMP(no object are loaded in $TMP, from the SAP file system). The newly created package is available in the SAP system, I can open it in SE80, even when I search for ABAP Object is being found, but when I cluck on it an error is displayed: Object not found in workspace.
