### ISSUE TITLE
Stuck on opening $TMP

### ISSUE THREAD

**Issue by filak-sap** [marcellourbani/vscode_abap_remote_fs#20]
I successfully connected to ABAP Trial running as Docker container, both the system and Visual Studio code are running on Fedora Linux.

Unfortunately, opening $TMP cause an infinite loop.

**Comment by marcellourbani** [comment]
Hi Jakub
On holiday this weekend, will have a look on Monday

**Comment by marcellourbani** [comment]
P. S. I think it's a poorly handled exception rather than an infinite loop

**Comment by filak-sap** [comment]
Oh dear, the dockerfile was tested on Fedora. I need to find a way how to publish my docker image. Stay tuned.

**Comment by marcellourbani** [comment]
That shouldn't matter, it's choking on the command line, which should only depend on the docker version (18.06.1-ce, build e68fc7a215 for the record)

**Comment by marcellourbani** [comment]
Btw, 0.0.2 had a similar problem with my 7.3 server, I think the fix is in
0.0.3

**Comment by filak-sap** [comment]
I built the vsix file from the current master, hence I don't think 0.0.3 addresses the issue.

**Comment by marcellourbani** [comment]
@filak-sap while I didn't do anything to fix this, error handling improved a lot.
You should now see an error message rather than an infinite loop.
PS: what SAP version was you using?

**Comment by christianguenter2** [comment]
same here
![image](https://user-images.githubusercontent.com/17437789/49873640-ae344280-fe1c-11e8-9dbc-d4a2c6e57dd7.png)

**Comment by marcellourbani** [comment]
@christianguenter2 is there any way you can give me access to a system?
It's hard to figure out what's causing it without debugging (won't have time in office hours anyway)

**Comment by christianguenter2** [comment]
I use a locally installed NW 752 SP01 dev system. It's not in the internet, so unfortunately no access. But you can easily setup the system yourself.

**Comment by marcellourbani** [comment]
already tried and failed, will have another go this weekend

**Comment by marcellourbani** [comment]
Ok, I now reproduced this on my own 7.52. Hope to get a fix by tomorrow

**Comment by marcellourbani** [comment]
@filak-sap @christianguenter2 I just published an update to fix this. Could you please confirm it works for you too?

Save still fails, but that's a different issue
