### ISSUE TITLE
"Failed to connect to ID8:AxiosError: Request failed with status code 404"- VS Code to SAP server connection issue

### ISSUE THREAD

**Issue by Dev4Develop** [marcellourbani/vscode_abap_remote_fs#202]
Hi @marcellourbani / Team,

Need your help to resolve the issue.

Context:  To connect SAP system from VS Code via "ABAP remote filesystem extension".
Our Demo SAP system is hosted on Azure cloud and VS code is in local system.

I followed all below instructions
1. ADT_SRV activated in SICF

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/74fc0055-a08a-473f-9d63-9f07da9ce901)

2. Test Service working
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/97fc4640-5786-4782-b391-f5148df94f9e)

3. Provided the same URL in Settings.json file 

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/aa095a0f-d307-4b88-a42e-6a40ae2cea9d)

Note that Fiori Launch pad is working. I'm aware its port 44300 as its https
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/f4bdbc0f-d5f5-4aab-8a62-83187d676463)

Also we are able to ping the server from terminal
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/0e6af3c9-81d6-40c1-be40-37ec7c6f017e)

**Comment by marcellourbani** [comment]
Hello
First of all, we need /sap/bc/adt, not /opu/...
Secondly, no need for / at the end of the URL.
Last, there's a known bug in certificate handling which might break tls connections

I do have a fix almost ready for the last one

Regards
Marcello

**Comment by Dev4Develop** [comment]
Thanks @marcellourbani . 

I've changed the URL without '/' but I still see the issue.

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/1b540b8c-07de-4833-858d-9aa6bcefe708)

**Is it because of the same certificate issue? If so, let me know when the fix will be available,**
> Last, there's a known bug in certificate handling which might break tls connections

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/137146462/236d4aa7-3a2f-4957-90d8-f4232e112ead)

**Comment by marcellourbani** [comment]
404 usually means you can't reach the server. Perhaps you need a proxy
