### ISSUE TITLE
$tmp function modules

### ISSUE THREAD

**Issue by virendevi234** [marcellourbani/vscode_abap_remote_fs#204]
Can not create, open the function modules part of **temp package**. This is possible for Programs and classes though.

**Comment by marcellourbani** [comment]
should work for your own objects

Support for objects owned by others was added fairly recently but only works when you search for them in the object search dialog

**Comment by marcellourbani** [comment]
@virendevi234 
I just remembered something: sometimes the object list gets corrupted and this extension is not able to rebuild it.

Refreshing the package contents in se80 usually does the trick

**Comment by marcellourbani** [comment]
Some recent updates should have fixed this, forgot to comment when I made them
