### ISSUE TITLE
How to connect to SAP ABAP system which allows only SNC as login and without password

### ISSUE THREAD

**Issue by koradaramjee789** [marcellourbani/vscode_abap_remote_fs#205]
Hi Experts,

How to connect to SAP ABAP system which allows only SNC as login and without password

Best wishes,
Ramjee Korada

**Comment by virendevi234** [comment]
Same question certainly beats me. Thanks

**Comment by marcellourbani** [comment]
Afraid that's not supported at the moment.
The only supported form of SSO is OAUTH, and I only tried that in BTP
#99 has been open forever because I don't have access to a SSO setup, and I'm not even trying to implement it without

How do you guys access UI5 applications? 

Regards
Marcello

**Comment by koradaramjee789** [comment]
Hello Marcello,

we access them using BAS from BTP. 

Can we install github co-pilot in BAS to use ABAP developments?

Best wishes,
Ramjee Korada

**Comment by marcellourbani** [comment]
Sadly this doesn't work in bas
Or at least it didn't last time I checked
But my question was about accessing ui5 apps as an end user, not as a
developer

**Comment by larshp** [comment]
if doing standalone ABAP development see https://community.sap.com/t5/application-development-blog-posts/using-ai-in-abap-development/ba-p/13573987

**Comment by rokk3r** [comment]
Hi Marcello,

joining the SSO club. In my company we are actually forced to do UI5 in BAS. And for local ABAP development SAP GUI resp. eclipse via SSO. It is all such a performance burner. But we call ourselves a "digital company". Local SAP logon without SSO is actually prohibited by admins. We don't get a password for our users. Now I am stuck trying out the remote-fs solution.

**Comment by rsteenkamp** [comment]
Hi Marcello,

I too face this problem.

In Eclipse, when we add a project, the following data is automatically displayed by Eclipse. 
<img width="417" alt="git_abap" src="https://github.com/user-attachments/assets/b1d6af41-cf9a-40f3-9ac4-0eed3b0b6fc9">

Is it possible that this information could point you in the direction to make SSO possible from VS code in the extension, please

**Comment by marcellourbani** [comment]
@rsteenkamp this only works over http(s)
If you use the base URL of your ui5 applications should work, as long as sicf node /sap/adt is enabled (noSSO though)
If that's not an option I'm afraid you're stuck with Eclipse

**Comment by rsteenkamp** [comment]
Thank you for the response. Marcello. I just got security to change my user
to non SSO.
