### ISSUE TITLE
Security of the extension

### ISSUE THREAD

**Issue by virendevi234** [marcellourbani/vscode_abap_remote_fs#206]
Hello,

Great job with the extension. Thanks for sharing as well.

To connect extension to my Dev system (behind firewall), first question is asked that is extension safe from networking and security standpoint, does it store personal data etc. How we can do the analysis?

Thank you.

**Comment by marcellourbani** [comment]
@virendevi234 well, the code is here :) 
Other than that, network is secure if you handle your tls properly, but the extension allows you to accept self signed certificates.
Only personal data it stores is passwords for your user (can be disabled) and git repos, if you use the abapgit integration.
Passwords go in the os secure store, so even that bit should be ok.
I don't do any telemetry, but maybe some npm package I use does, who knows?

Marcello
