### ISSUE TITLE
Package and Data element creation issue

### ISSUE THREAD

**Issue by info4Narayana** [marcellourbani/vscode_abap_remote_fs#207]
Hi @marcellourbani / Team, 

Need your help to resolve the issue.

We are using ABAP remote FS in VS code to create a package and data elements in SAP ECC but ended with error Error 404:Not Found. Kindly refer the attached document for VS code and SAP error details in the attached.

[VS code Error log.docx](https://github.com/marcellourbani/vscode_abap_remote_fs/files/14408408/VS.code.Error.log.docx)

Best Regards,
Narayana

**Comment by marcellourbani** [comment]
Hello @info4Narayana 
Looks like an ABAP version issue: your system is either too old or too new for that functionality. Afraid you'll have to do this in eclipse or sapgui
Hopefully most of the rest will work.

What ABAP version are you on?

Best regards,
Marcello

**Comment by info4Narayana** [comment]
Hi Marcello,

Thanks a lot for swift response. 
Please find the print screen for SAP ECC Version details.

![4d87b1ae-afe4-47d5-82a1-70d724aaa467](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/160339921/97bd3d45-d89e-4159-bf9c-3dec3fcf357a)

**Comment by marcellourbani** [comment]
@info4Narayana yep, it's aversion issue.
I think the eclipse API I use to do that is available since 7.5 or so. Maybe there's an older one who is, but I don't support it.
Please stick to eclipse/se80 for this. You can probably use vscode for the rest

Marcello
