### ISSUE TITLE
Crash on Mac VS Code due to embedded Source code control management

### ISSUE THREAD

**Issue by yunze-wang** [marcellourbani/vscode_abap_remote_fs#208]
Hello,
It seems like when you try to open a workspace for an ABAP system, the embedded SCM is going to scan all the files under this project(means the whole system repository) to find out the changed files. I'm not sure if it's a bug for this plugin or the VS Code itself.
Yunze

**Comment by marcellourbani** [comment]
Hello
This might well be linked to some other extension or configuration.
Could you please try with an empty profile with only this extension (and its dependencies of course)?

Marcello
