### ISSUE TITLE
Modification of newly created FM

### ISSUE THREAD

**Issue by maggiv8** [marcellourbani/vscode_abap_remote_fs#214]
Hi Marcello

I do seem to have an issue when creating and afterwards trying to activate modificiations in a new Function Module - at least on my setup
A) Steps to reproduce issue:
1. Create Function Module Group.
2. Create Function Module for this group (I am getting an error here as well, but the FM gets ultimately create in the backend system)
3. Save and activate Function Module.
4. Make changes on Function Module code level (e.g. new IF statement) and activate again.

Current result:
The code changes after the initial activation cannot be seen in SAP GUI on the Function Module.

Expected result:
The changes after the initial activation should be seen in SAP GUI on the Function Module.

Not sure if you are experiencing a similar or same issue.
If you please could have a look at it, it would be appreciated.

Thank you.
Best,
C.

**Comment by marcellourbani** [comment]
Never happened to me, probably depends on what ABAP version you're running.
What happens if you refresh the FG contents in se80?
I do have some issue within the editor in these cases, and usually work
around it either refreshing the function group in the tree or restarting
the editor, so there's definitely something not right there

**Comment by maggiv8** [comment]
Hi Marcello,

I tried to refresh the content, but it doesn't relaly do anything. The FM always just contains the original content of the first commited version so to speak.
If you want to debug it, I can give you access to the system via email.

Thank you.
Best,
C.

**Comment by maggiv8** [comment]
I am using S4/2021 with SAP_BASIS 756, SAP_ABA 756G.

**Comment by marcellourbani** [comment]
Next version should fix it

**Comment by maggiv8** [comment]
Awesome, thank you Marcello.
