### ISSUE TITLE
Debugging ABAP with VS Code

### ISSUE THREAD

**Issue by maggiv8** [marcellourbani/vscode_abap_remote_fs#217]
Please see comment below for details

**Comment by maggiv8** [comment]
Hi there,

after using VS Code now for a few of my developments I am still struggling with using the debug functionality.
I do have a dummy report in my local repository (i.e. ‘$tmp’). Here are the steps I am performing when trying to start debugging:
1. Set breakpoint:
![Screenshot from 2024-05-06 13-18-22](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/134909188/110a72f6-7dd5-439a-969e-573b86046555)

2. Click on ‘Run → Start Debugging’ (or ‘F5 alternatively)’.
3. VS code connect ot the ABAP server:
![Screenshot from 2024-05-06 13-23-37](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/134909188/a9fb243f-e3dc-4275-9a73-cbc6a570a509)


4. However, it doesn’t stop at the breakpoint I have set even when clicking on ‘Restart’ (or ‘Ctrl’ + ‘Shift’ + ‘F5’).

I have checked a few tutorials online about Debugging ABAP on VS Code, but somehow I can’t convince VS Code to stop at my breakpoint.

Any help would be highly appreciated.
Thank you.
Best,
C.

**Comment by marcellourbani** [comment]
SapGUI debugging is not supported, as requires contolling it and I don't know how.
sbsp unit , RFC cannl and webservices work ok

**Comment by maggiv8** [comment]
@marcellourbani : I understand from your comment that based onthe current release you cannot debug reports for example. Thank you for claryfing. 
However, it seems you can create a unit test for a class und then test this class if I understand the following blog from you correctly: https://community.sap.com/t5/application-development-blog-posts/debugging-abap-in-visual-studio-code/ba-p/13500931

How exactly do you do that and what are the steps to trigger such a unit test with debugging enabled? For example:
I created a class, pressed 'F5' for debug and then 'Ctrl + shift + F11' for unit testing, but it stil ldoesn't stop at the set breakpoint. Any more help and guidance would be highly appreciated.
Thank you.

**Comment by marcellourbani** [comment]
That should work
If you give me access I can troubleshoot

**Comment by marcellourbani** [comment]
@maggiv8 
Your demo class has no unit test.
I created one who does and debugger works fine:

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/2453277/24bba80c-e8dd-4537-8fce-fe48c0f0a1ab)

**Comment by maggiv8** [comment]
@marcellourbani : thank you so much for clarifying. It works now :+1:
