### ISSUE TITLE
Supporting VSCode for the web

### ISSUE THREAD

**Issue by kartefact** [marcellourbani/vscode_abap_remote_fs#218]
![Screenshot_20240508-210117.png](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/3407499/bbb80c53-13c1-46c7-9394-2eab6687312a)

Does the roadmap contain support for the web version of VSCode? 

Not sure how involved the changes would be.

**Comment by larshp** [comment]
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) will be a problem, to solve it then you'd have to run a proxy, if its possible to run a proxy then might as well run normal vscode

editing files in a git repository works, push and pull with abapGit into/from systems

also https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint works in web, as its standalone

**Comment by marcellourbani** [comment]
Yes, I did give it a go and gave up pretty quickly because of CORS. It's not the only issue, but it's the one we can't work around. Except by using a proxy or serving vscode from the ABAP instance
