### ISSUE TITLE
Endless state "UI5Plugin: Initializing ..."

### ISSUE THREAD

**Issue by Stony111** [marcellourbani/vscode_abap_remote_fs#221]
Hello,
today I tried to install the extension - unfortunately without success! After installation I can configure a system connection. But whe I want to connect to this system, after confirming password input with enter, nothing happens. 
On the left side in the navigation tree, busy indicator is running an in status bar on the bottom of the vs code window the state "UI5Plugin: Initializing" will endless shown.

![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/103322602/db84a813-eed5-494d-9b4e-2faa739ceec8)

Has anybody an idea what the problem can be? Accessing with eclipse to the same system works fine without problems. So I don't think, that it is a server issue!

Thanks a lot for any tipp!

Best regards
Martin

**Comment by marcellourbani** [comment]
Hi
This is a new one!
Can you please try disabling the UI5 extension, just to see if it fixes the problem?
Also, can you please show me the abap fs output channel?
![image](https://github.com/user-attachments/assets/4b8f8cc2-043d-456d-833e-c3317d1a2be4)
Cheers
Marcello

**Comment by Stony111** [comment]
Hi Marcello,
first of all thanks for your fast reply. Here is the output of the abap fs channel:
![image](https://github.com/user-attachments/assets/2dfdc55a-cc99-41a8-97ed-72f2caa99ee4)

Next I tried to find a extension with UI5 in name and I can only find this one in the list of installed extension:
![image](https://github.com/user-attachments/assets/81935a86-99c1-4427-931d-44b37c948172)

... and what should I say - after disabling this extension abap fs seems to run. The endless state of UI5 Initialization doesn't appear and when I click for example on the node $TMP or "System library" the result is shown in a few seconds. Editing classes an so on is now possible. 

At the moment I can't say what it means to leave the UI5 extension deactivated for my work.
Before installing abap fs, however, there were no problems with the extension. Somehow the two don't seem to get along.

Thanks a lot for your support.

Best Regards
Martin

**Comment by marcellourbani** [comment]
@Stony111 You can enable/disable extension on a per workspace basis
I would recommend to disable it in current workspace before connecting, and then saving it.

When you open it again will be disabled already, but only there
Will see if I can get them to work togethersomehow

**Comment by Stony111** [comment]
... thanks for your support. I will disable the extension in my ABAP workspace ...
