### ISSUE TITLE
ABAP 7.58 - No SICF adt_srv service available

### ISSUE THREAD

**Issue by Incho77** [marcellourbani/vscode_abap_remote_fs#222]
In ABAP 7.58 there is no SICF adt_srv service available anymore.
Connection doesn't work.

Any idea how to make it work for ABAP 7.58 system?
Any info/hint is welcome. Thanks!

**Comment by marcellourbani** [comment]
sorry, no idea
Will require some hack I guess

In theory I could use RFC instead, but can't embed it in a vscode extension, and would have copyright issues anyway

**Comment by Incho77** [comment]
Hi Marcello,
Thanks for your quick reply.
I'll keep trying, maybe I will find the way.
I'm closing the issue, it makes no sense to keep it open now.
Best regards,
Peter
