### ISSUE TITLE
Cannot read properties of undefined (reading 'asx:values')

### ISSUE THREAD

**Issue by pamMtz** [marcellourbani/vscode_abap_remote_fs#223]
Hello, everyone
I have configured the ABAP remote FS and I can open the abap programs in VS.
However, I can't save any modifications to the files.
Currently working with 
SAP ERP 6.0 2005 SP 24

I always get this error:

Error writing file adt://dev/System%20Library/Z001/Source%20Library/Programs/Z_RH_TEST/Z_RH_TEST.prog.abap
Cannot read properties of undefined (reading 'asx:values')

When I create any other program:

Exception in createAdtObject:TypeError: Cannot read properties of undefined (reading 'asx:values')
    at n.transportInfo (c:\Users\ppatena\.vscode\extensions\murbani.vscode-abap-remote-fs-1.7.11\client\dist\extension.js:2:1531707)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at u (c:\Users\ppatena\.vscode\extensions\murbani.vscode-abap-remote-fs-1.7.11\client\dist\extension.js:2:3687486)
    at AdtObjectCreator.createObject (c:\Users\ppatena\.vscode\extensions\murbani.vscode-abap-remote-fs-1.7.11\client\dist\extension.js:2:3726633)
    at Function.createAdtObject (c:\Users\ppatena\.vscode\extensions\murbani.vscode-abap-remote-fs-1.7.11\client\dist\extension.js:2:3750696)
    at f.h (c:\Users\ppatena\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:204392)
Error reading directory adt://dev/System%20Library/%E2%88%95IBMT%E2%88%95UTILITY/Source%20Library/Classes/%E2%88%95IBMT%E2%88%95EXCEL07_ADAPTER
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_APPLICATION/%E2%88%95IWBEP%E2%88%95740_SAMPLE_BASIC/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_GWSAMPLE_BAS_DPC
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_APPLICATION/%E2%88%95IWBEP%E2%88%95740_SAMPLE_BASIC/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_GWSAMPLE_BAS_DPC_EXT
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_APPLICATION/%E2%88%95IWBEP%E2%88%95740_SAMPLE_BASIC/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_GWSAMPLE_BAS_MPC
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_APPLICATION/%E2%88%95IWBEP%E2%88%95740_SAMPLE_BASIC/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_GWSAMPLE_BAS_MPC_EXT
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_SERVICE_BUILDER/%E2%88%95IWBEP%E2%88%95SB_WB_EXTENSION/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_ADT_GUI_INTEGRATION
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_SERVICE_BUILDER/%E2%88%95IWBEP%E2%88%95SB_WB_EXTENSION/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_ADT_URI_MAPPING
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_SERVICE_BUILDER/%E2%88%95IWBEP%E2%88%95SB_WB_EXTENSION/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_WB_ACCESS
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_SERVICE_BUILDER/%E2%88%95IWBEP%E2%88%95SB_WB_EXTENSION/Enhancements/Enhancement%20Implementations/%E2%88%95IWBEP%E2%88%95ADT_GUI_INTEGRATION
Operation not supported for object ENHO/XH /IWBEP/ADT_GUI_INTEGRATION
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95740_EXTENSIONS/%E2%88%95IWBEP%E2%88%95740_SERVICE_BUILDER/%E2%88%95IWBEP%E2%88%95SB_WB_EXTENSION/Enhancements/Enhancement%20Implementations/%E2%88%95IWBEP%E2%88%95ADT_URI_MAPPING
Operation not supported for object ENHO/XH /IWBEP/ADT_URI_MAPPING
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95MAIN/%E2%88%95IWBEP%E2%88%95BEP/%E2%88%95IWBEP%E2%88%95BEP_COMMON/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_LOGGER
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95MAIN/%E2%88%95IWBEP%E2%88%95BEP/%E2%88%95IWBEP%E2%88%95BEP_COMMON/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CX_EVENT_PUBLISHER
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95MAIN/%E2%88%95IWBEP%E2%88%95BEP/%E2%88%95IWBEP%E2%88%95BEP_DT/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_C_EVENT
Cannot read properties of undefined (reading 'href')
Error reading directory adt://dev/System%20Library/%E2%88%95IWBEP%E2%88%95FRAMEWORK/%E2%88%95IWBEP%E2%88%95MAIN/%E2%88%95IWBEP%E2%88%95BEP/%E2%88%95IWBEP%E2%88%95BEP_DT/Source%20Library/Classes/%E2%88%95IWBEP%E2%88%95CL_SYSTEMS
Cannot read properties of undefined (reading 'href')

**Comment by marcellourbani** [comment]
weird 
What abap basis are you running?

Marcello

**Comment by pamMtz** [comment]
![imagen (3)](https://github.com/user-attachments/assets/212436a7-15bb-41d9-bab2-81a5e90c99b3)

**Comment by marcellourbani** [comment]
sorry, I have no idea. Would need access to the system to find out

**Comment by miaomiao-wzs** [comment]
![Image](https://github.com/user-attachments/assets/bc243ff7-fb56-4371-9cc8-4520410531db)
Cannot read properties of undefined (reading 'tagName')
Cannot read properties of undefined (reading 'asx:values')

The connection was successful, but no tabs are displayed

![Image](https://github.com/user-attachments/assets/13cf0ee8-3659-45f0-910c-32cdc826454b)

**Comment by miaomiao-wzs** [comment]
> [@miaomiao-wzs](https://github.com/miaomiao-wzs) would you be able to send me the whole dump in html? If not, can you please make a screenshot of the active calls section and the source code where it happened?

There was no dump, I just took a screenshot of the system dump interface to verify that I had connected to the sap system through vscode, but when I opened the folder to view the program in the file management interface, I got an error message。

Cannot read properties of undefined (reading 'asx:values')
Cannot read properties of undefined (reading 'tagName')

**Comment by Wsssi** [comment]
> ![Image](https://github.com/user-attachments/assets/bc243ff7-fb56-4371-9cc8-4520410531db) Cannot read properties of undefined (reading 'tagName') Cannot read properties of undefined (reading 'asx:values')
> 
> The connection was successful, but no tabs are displayed
> 
> ![Image](https://github.com/user-attachments/assets/13cf0ee8-3659-45f0-910c-32cdc826454b)

This issue has been resolved in the latest version of the plugin. Thank you very much to the author
