### ISSUE TITLE
A request has failed(self signed certificate ). See the output for more information.

### ISSUE THREAD

**Issue by COOPER-DENG** [marcellourbani/vscode_abap_remote_fs#224]
HI,
   When I edit the ABAP code, the output console displays "Exception in syntax check: self signed certificate "; when I click the activate button, the prompt "A request has failed. See the output for more information."
   When connecting to abap system, I have imported the certificate to my computer, so the connection is successful, but why is "self signed certificate" still displayed here? 
![image](https://github.com/user-attachments/assets/ffa80a11-4db8-41ed-9819-ae0299644d1d)
![image](https://github.com/user-attachments/assets/fa288bba-7b96-42c1-b175-5d797af9849f)

  Cooper,
  Best wishes.

**Comment by marcellourbani** [comment]
Hi @COOPER-DENG Self signed certificates are supported, but I had mixed results recently
to be clear: you can edit files but language features fail with that message, right?
Can you send me your configuration (censoting passwords and similar of course)

**Comment by COOPER-DENG** [comment]
> Hi @COOPER-DENG Self signed certificates are supported, but I had mixed results recently to be clear: you can edit files but language features fail with that message, right? Can you send me your configuration (censoting passwords and similar of course)

HI, @marcellourbani ,
 YES, the ABAP program can be edited and activated correctly, but the output panel always displays messages related to "self signed certificate"

[output.txt](https://github.com/user-attachments/files/17469045/output.txt)
![Snipaste_2024-10-22_10-21-28](https://github.com/user-attachments/assets/14a2ad8e-243a-423e-87f7-4a85906e9d98)

Cooper,
Best wishes.

**Comment by marcellourbani** [comment]
so the url is a domain name, and the server an ip number?

**Comment by COOPER-DENG** [comment]
> domain name

HI,@marcellourbani ,
Yes, does it have something to do with this? I just changed the SERVER IP to the same domain name as the URL, and the result is still the same as before, no change.
change.
The SAPGUI parameter is only optional. I also tried to delete it, but the result remained unchanged after deletion.
Cooper,
Best wishes.

**Comment by marcellourbani** [comment]
Really weird. If I have to guess, I would say that:

- your server uses a self-signed certificate
- some other extension sets an environment variable to accept self signed certificate (**BAD** idea, but I've seen it done)
- the language server is not affected

Setting  `"allowSelfSigned": true`  should do the trick

**Comment by COOPER-DENG** [comment]
> Exception in syntax check: self signed certificate

HI, @marcellourbani ,
YES,allowSelfSigned":true , it worked, it's the ultimate weapon. Thank you very much.

Cooper,
Best wishes.
