### ISSUE TITLE
Error 400:Session timed out Won't be able to save changes  AND How to match code blocks and how to jump to the include program

### ISSUE THREAD

**Issue by COOPER-DENG** [marcellourbani/vscode_abap_remote_fs#225]
HI,
a . When I did not use VSCODE for a period of time, the connection was automatically disconnected and "Error 400: Session timed out Won't be able to save changes" was displayed. Then I tried to execute the connect to ABAP system command again and clicked on the workspace Refresh button, but this error still appears. I had to close VSCODE and reopen it to solve the problem. Is there any other better way?

b. How to open an include program in a program, like you can double-click to jump in ADT, can it be implemented here?

c.How to jump in a code block, such as IF...ESLE...ENDIF, such as jumping from IF to ELSE or ENDIF. I know that the shortcut key Ctrl + Shift + \ can jump from IF to ENDIF, but It is impossible to jump from IF to ELSE. If such a code block is very long or the code block is nested, it can quickly jump to the corresponding location is very useful

Cooper,
Best wishes.

**Comment by marcellourbani** [comment]
yep, always bothered me too.
Doesn't work for now, maybe I'll try to get it done in future

**Comment by COOPER-DENG** [comment]
> yep, always bothered me too. Doesn't work for now, maybe I'll try to get it done in future
HI,@marcellourbani,

I understand, thank you for your great efforts, come on!

Cooper,
Best wishes.

**Comment by COOPER-DENG** [comment]
HI,@marcellourbani,
I see that there have been some changes, a. The connection does not seem to be disconnected automatically, b. It seems that I can jump between code blocks, c.include program can also be jumped and opened directly. I guess you should have done  some adjustments.

Cooper,
Best wishes.

**Comment by marcellourbani** [comment]
Fixed the session timeout, block navigation I guess it's hit and miss
