### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by COOPER-DENG** [marcellourbani/vscode_abap_remote_fs#230]
HI,
I found that the debug function cannot be used. What are the specific steps required?
![image](https://github.com/user-attachments/assets/2ee128ca-cf31-4490-b9ab-511c524e39d1)
![image](https://github.com/user-attachments/assets/299454f4-ab1d-4040-8711-e21b7a548446)
![image](https://github.com/user-attachments/assets/5b15099b-b72c-40ba-9c05-656bfc6fa7ef)

Cooper,
Best wishes.

**Comment by marcellourbani** [comment]
Just pressing F5 should work. Doesn't work with sapgui

**Comment by COOPER-DENG** [comment]
> Just pressing F5 should work. Doesn't work with sapgui

Hi,
Why is the debug button on the third picture above is gray and unavailable when I press F5

**Comment by COOPER-DENG** [comment]
> 因为它已经处于活动状态 如前所述，没有 SAPGUI，所以在程序中你只能调试单元测试 RFC 和 HTTP 调用也可以工作

@

> 因为它已经处于活动状态 如前所述，没有 SAPGUI，所以在程序中你只能调试单元测试 RFC 和 HTTP 调用也可以工作



> because it's active already As said, no SAPGUI so in programs you can only debug unit tests RFC and HTTP calls also work

HI,
Okay, then I will use debug in GUI or ADT.
