### ISSUE TITLE
Object not found in workspace

### ISSUE THREAD

**Issue by COOPER-DENG** [marcellourbani/vscode_abap_remote_fs#232]
HI @marcellourbani ,
    This extension is no longer available now.What has been updated recently?
    When I use the command AbapFs Search for object to search for an include program named ZPPF021A_FUN, I searched for it, but when I try to open,an error of "Object not found in workspace" is displayed, but ZPPF021A_FUN I am sure it exists and I can edit it in SE38.
     After my testing, I found that the include programs I just created cannot be opened normally, but the previously existing include programs are not affected.
This means that my newly created include  programs will not be able to open, which is too bad, I'm waiting for you to fix it now.
![image](https://github.com/user-attachments/assets/4d8470b0-f53e-44d4-9753-d35ebf91b011)

Cooper,
Best wishes!

**Comment by marcellourbani** [comment]
Hi Cooper
Sometimes this can be fixed by refreshing the package index or the object index in SE80
If it's not that I would have a tough time fixing it until happens to me/have access to a failing system

Cheers
Marcello

**Comment by COOPER-DENG** [comment]
> Hi Cooper Sometimes this can be fixed by refreshing the package index or the object index in SE80 If it's not that I would have a tough time fixing it until happens to me/have access to a failing system
> 
> Cheers Marcello

HI Marcello,
I have refreshed as you said and it works. Thank you very much. I am very happy to have this temporary solution,So no need to worry.

Cooper,
Best wishes!

**Comment by marcellourbani** [comment]
I never worry, I write this for myself.
If it works for you too that's great, but don't loose any sleep if it doesn't

PS: I don't know if you realise it, but your comments above sound a bit rude, I didn't take offense because you're clearly not a native speaker

Take care
Marcello

**Comment by COOPER-DENG** [comment]
> I never worry, I write this for myself. If it works for you too that's great, but don't loose any sleep if it doesn't
> 
> PS: I don't know if you realise it, but your comments above sound a bit rude, I didn't take offense because you're clearly not a native speaker
> 
> Take care Marcello

Hi,Marcello,

I use Google Translate to communicate with you. I actually want to comfort you above.I'm very sorry that you had a bad feeling, it was not my original intention. Thank you again for this project, I will try my best to organize my words, thank you for your reminders and corrections .

Cooper,
Best wishes!
