### ISSUE TITLE
pretty printer

### ISSUE THREAD

**Issue by marcellourbani** [marcellourbani/vscode_abap_remote_fs#37]

**Comment by Leoooob** [comment]
is this still in the works? i'd absolutely love this feature, using the abap-linter for this specifically has been a pain. Every time i connect to a system the linter scans every object which effectively locks me out of the linter menu.

**Comment by marcellourbani** [comment]
@Leoooob yes this is done. Happens at every save if enabled in code or when you invoke the format document command (Ctrl+Shift+I by default)

**Comment by Leoooob** [comment]
thanks for the swift response but this has given me an error when i run format document:

```
Exception in document symbol: Error: Request vscabap.readConfig failed with message: Cannot destructure property `sapGui` of 'undefined' or 'null'.
```

if this isn't something you've seen before, i can open an issue for it?

**Comment by marcellourbani** [comment]
I think there's a bit of a misunderstanding.
This thing doesn't work for local files, only remote SAP systems connected over https.
A bit like Eclipse
