### ISSUE TITLE
"TypeError: Cannot read propery 'scheme' of undefined" on activation

### ISSUE THREAD

**Issue by christianguenter2** [marcellourbani/vscode_abap_remote_fs#57]
When I try to activate a report (or class) on NW 752 SP01 dev edition I get this error.
"TypeError: Cannot read propery 'scheme' of undefined"

![image](https://user-images.githubusercontent.com/17437789/54933968-fa177d00-4f1d-11e9-8cb3-ca35f3e4d9dd.png)

**Comment by marcellourbani** [comment]
@christianguenter2 do you have any debug information in the output panel?

![image](https://user-images.githubusercontent.com/2453277/54939298-203e1c80-4f20-11e9-8c17-c9512b757a54.png)

Anyway should be easy enough to find, it's surely a missing undefined check

**Comment by christianguenter2** [comment]
hm, nothing there.
![grafik](https://user-images.githubusercontent.com/17437789/54947059-bb8fbb80-4f39-11e9-8897-90c1c3c6f380.png)

**Comment by marcellourbani** [comment]
Wrong selection, that's abaplint :)

Almost surely was this:

![image](https://user-images.githubusercontent.com/2453277/54962249-fc98c780-4f5b-11e9-8054-13ff307178fc.png)

and the next release will fail more gracefully, but should never happen if you run it with the button.
If you run it from the command palette though, it won't get the right URI in the caller. Will look better tomorrow.

**Comment by christianguenter2** [comment]
Sorry, I obviously don't know what I'm doing ;-)
![image](https://user-images.githubusercontent.com/17437789/54982326-e9611880-4faa-11e9-8dbf-90e1be1cd12e.png)

**Comment by marcellourbani** [comment]
@christianguenter2 I just published a new release which among other things *should* fix this issue, at least by failing nicely.

Did you start the release command with the icon or manually from the command palette?

**Comment by christianguenter2** [comment]
Great, now it works.
I started the activation from the command palette. Didn't know there's an icon ;-)

Thanks a lot and keep going with this great work. Closing.

**Comment by marcellourbani** [comment]
Great, thanks!

It's starting to get usable, but has so many bugs!
