### ISSUE TITLE
Unknown error in adt client

### ISSUE THREAD

**Issue by FreHu** [marcellourbani/vscode_abap_remote_fs#62]
I haven't managed to connect successfully so far due to the local issuer certificate error. Allowing self signed or specifying customCa will show 

![image](https://user-images.githubusercontent.com/5097067/55399166-a7a41500-554a-11e9-87e5-23669e0cf7d3.png)

Is there any way to get to the error so I can figure out what's going on?

**Comment by soydepr** [comment]
Try not using certificate

**Comment by FreHu** [comment]
I get a connection refused error if I try to go through HTTP:
![image](https://user-images.githubusercontent.com/5097067/55400273-acb69380-554d-11e9-88be-c1fd6119edc3.png)

Again, it would be helpful if I could see a detailed error.

**Comment by marcellourbani** [comment]
@FreHu 
there's an ABAP FS output channel where I log many (not all) errors
![image](https://user-images.githubusercontent.com/2453277/55400114-e2a34a00-5544-11e9-9251-ebdeea067a7d.png)

Can you access with Chrome to something like say /sap/bc/adt/programs/programs/zabapgit/source/main

**Comment by marcellourbani** [comment]
also, can I see your connection details (without pwd of course!)

**Comment by FreHu** [comment]
```
"ER9": {
        "url": "https://ldcier9.wdf.sap.corp:44300",
        "client": "500",
        "language": "EN",
        "allowSelfSigned": true,
        "customCA": "C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt"
      },
```
I tried all variants of http(s), 44300, 8080, with/without the cert, with the SAP root cert, etc.
Adding the SAP certificates to ca-bundle was what got vscode to stop complaining in the terminal, but doesn't seem to help.

Unfortunately the log only shows `connecting to server`
![image](https://user-images.githubusercontent.com/5097067/55400851-429eee00-554f-11e9-9f85-e279c6203638.png)

**Comment by marcellourbani** [comment]
All looks fine, except you do need to specify a password in there (I assume you censored it, but just in case...) as it won't prompt you about it.
Again, can you open [this link](https://ldcier9.wdf.sap.corp:44300/sap/bc/adt/programs/programs/zabapgit/source/main) in chrome?

**Comment by FreHu** [comment]
Yes, in the real config I have a username and password. The link opens normally.

**Comment by marcellourbani** [comment]
no idea what it could be.
I guess I will try to enhance logging. Will ping you after I did so.

Looks like it's happening very near the beginning, will go through that.

BTW, what version of ABAP is that?

**Comment by FreHu** [comment]
The system runs on the latest SAP S/4HANA 1909 release.

I can also try installing a vsix if you don't want to have to update the plugin.

**Comment by marcellourbani** [comment]
Ok.Or I might create a nodejs application to test the basics and send you
that instead (not today, I plan to go out)

**Comment by marcellourbani** [comment]
Looks like this was mostly a configuration issue.
I did improve error handling and opened a couple other issues for bugs more or less related to this

**Comment by juanbausa** [comment]
Hi. I am also encountering the same issue. I am connected to a vpn with only intranet access.

**Comment by marcellourbani** [comment]
Did you try to set allowselfsigned?

**Comment by juanbausa** [comment]
> Did you try to set allowselfsigned?

Yes
