### ISSUE TITLE
adding favorite does not work

### ISSUE THREAD

**Issue by arcanist123** [marcellourbani/vscode_abap_remote_fs#85]
the add favorite does not seem to be doing anything
https://i.imgur.com/aceLeTR.png
my expectation would be that it proposes the option to select the package. Instead it does nothing

**Comment by marcellourbani** [comment]
I guess there's a documentation issue here, will add it to the wiki.
Also, adding the root as favorite (which doesn't make much sense anyway) doesn't currently work.
Will fix that before closing this (perhaps with a warning)

![vsc_favourites](https://user-images.githubusercontent.com/2453277/58316594-2f542480-7e14-11e9-99dd-76fa8944cd79.gif)

**Comment by arcanist123** [comment]
I see. I guess, this is not an issue at all. Thanks for the clarification

**Comment by cawoodm** [comment]
Apparently it now adds `/` favorites when you do this:
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/498834/e3bb82df-b332-4347-83f3-90f00f74b8ec)

Perhaps this is desire behaviour - however duplication of favorites probably isn't.

IMHO it would be nicer just to add favorites just to the normal workspace tree here:
![image](https://github.com/marcellourbani/vscode_abap_remote_fs/assets/498834/99e0becb-7ea7-4c85-a367-53b84f2373a7)

**Comment by marcellourbani** [comment]
Afraid it wouldn't play nice with code
