### ISSUE TITLE
create method definition dumps with 7.52 ABAP Trial

### ISSUE THREAD

**Issue by arcanist123** [marcellourbani/vscode_abap_remote_fs#86]
Hello.

It looks like the quick fix for creation of definition of method fails. 
Step to reproduce:
1. Create a simple class zcl_test_001 with the content as below
[code.txt](https://github.com/marcellourbani/vscode_abap_remote_fs/files/3214403/code.txt)

2. Try to generate the method as per the screenshot
![fix](https://user-images.githubusercontent.com/8202327/58291756-d73f0300-7dbe-11e9-8c7e-d3c99e38620c.png)

3. the system dumps 
[dump.txt](https://github.com/marcellourbani/vscode_abap_remote_fs/files/3214405/dump.txt)

**Comment by marcellourbani** [comment]
Hi it did happen to me a couple of times, but turned out to be a SAP backend issue: I got exactly the same dump with Eclipse

Doesn't imply it's the same in this case, so my question is: what happens if you do the same with Eclipse?
This plugin uses pretty much the same APIs, but I might have messed up some parameter

**Comment by arcanist123** [comment]
Hello.
Sorry for the sloppy responce - there was a need to reinstall my netweaver and this is not the fastest thing to do
so, the quick fix is working in eclipse. 
Before quick fix
![apply_quick_fix](https://user-images.githubusercontent.com/8202327/58366294-70aa0a00-7ed0-11e9-952c-7c3a18b574c7.png)
After applying
![quick_fix_applied](https://user-images.githubusercontent.com/8202327/58366295-7869ae80-7ed0-11e9-8df0-dc6e3f768188.png)

**Comment by marcellourbani** [comment]
I did manage to reproduce this in house, didn't have time to fix it yet

**Comment by marcellourbani** [comment]
@arcanist123 
The latest release fixed it for me
