### ISSUE TITLE
SAPGui not opened in macOS

### ISSUE THREAD

**Issue by agoeb** [marcellourbani/vscode_abap_remote_fs#89]
When pressing `F5` in an open editor, a SAPGui dialog appears, reporting an internal error saying "invalid data received". I suppose this is due to the SAPGui for Java somehow not being able to parse the generated `.sap` file.

Full error is: 

> Connection failed
> Error: internal error
> Mon Jul 22 11:58:24 2019
> Release 753
> Component NI (network interface), version 40
> rc = -1, module
> /net/usr.delivery/SAPGUIForJava_750_REL/bas_753_REL/src/base/ni/nibuf.cpp, line
> 2769
> Detail NiBufIIn: invalid data received
> Technical Details
> java.lang.Exception: Error: internal error
>  
> Mon Jul 22 11:58:24 2019
> Release 753
> Component NI (network interface), version 40
> rc = -1, module /net/usr.delivery/SAPGUIForJava_750_REL/bas_753_REL/src/base/ni/nibuf.cpp, line 2769
> Detail NiBufIIn: invalid data received
> 
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.processOpenRequest(GuiNiNetConnection.java:329)
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.handleOpenRequest(GuiNiNetConnection.java:158)
> at: com.sap.platin.base.connection.GuiConnection.processCreateReply(GuiConnection.java:537)
> at: com.sap.platin.base.connection.GuiConnection.handleCreateReply(GuiConnection.java:510)
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.handleCreateRequest(GuiNiNetConnection.java:148)
> at: com.sap.platin.base.connection.GuiConnection.open(GuiConnection.java:334)
> at: com.sap.platin.base.application.GuiApplication.createConnection(GuiApplication.java:979)
> at: com.sap.platin.base.logon.ConnectionDocumentReader$3.run(ConnectionDocumentReader.java:462)
>  
> caused by : java.io.IOException
> java.io.IOException
> at: com.sap.platin.r3.protocol.ni.JniAgComAdaptor.connect(JniAgComAdaptor.java:44)
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.processOpenRequest(GuiNiNetConnection.java:288)
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.handleOpenRequest(GuiNiNetConnection.java:158)
> at: com.sap.platin.base.connection.GuiConnection.processCreateReply(GuiConnection.java:537)
> at: com.sap.platin.base.connection.GuiConnection.handleCreateReply(GuiConnection.java:510)
> at: com.sap.platin.r3.protocol.ni.GuiNiNetConnection.handleCreateRequest(GuiNiNetConnection.java:148)
> at: com.sap.platin.base.connection.GuiConnection.open(GuiConnection.java:334)
> at: com.sap.platin.base.application.GuiApplication.createConnection(GuiApplication.java:979)
> at: com.sap.platin.base.logon.ConnectionDocumentReader$3.run(ConnectionDocumentReader.java:462)

**Comment by marcellourbani** [comment]
Could you please send me a copy of that .sap file, perhaps censoring what needs to?
This works fine on my linux and windows boxes, no idea who else tied it.

**Comment by agoeb** [comment]
Sure! I'm happy to provide details. Currently, I cannot even figure out where that file is supposed to be created.  It looks like the `sapgui.ts` assumes some default directory, and I'm not into VSCode extensions, so I just don't know where to look. Could you please guide me in the right direction?

**Comment by marcellourbani** [comment]
Should be in your temp directory, like /tmp for linux.

Might also be deleted pretty quickly by the extension, as it's a bit of a backdoor

**Comment by agoeb** [comment]
Thanks! Now that I know where to look, the problem has vanished. I seems that restarting VSCode (or SAPGui) has fixed it for some reason. 
Closing the issue, since I cannot reproduce it anymore. Thanks for the great support!
