### ISSUE TITLE
Cannot connect to a System

### ISSUE THREAD

**Issue by KaiMildner** [marcellourbani/vscode_abap_remote_fs#93]
Hi.

I wanna try your plugin to connect with our SAP system. Connecting with Eclipse is working, but when i try to connect with VS Code using your plugin i get the Error.

![image](https://user-images.githubusercontent.com/46740508/65151714-f70dcd00-da26-11e9-8acf-d4ad3ada8c84.png)

What have i done:

1. Installed your plugin
2. press F1
3. Select: ABAPfs Connect to an ABAP system
4. The error popup opens.

So in the end i'm not able to create a connection.

Maybe i did something wrong or forgot something?

Regards

Kai

**Comment by marcellourbani** [comment]
Hi Kai,
Sadly the setup is still manual
You have to create a connection entry in your settings file, like this:
```json
{
  "abapfs.remote": {
    "NPL": {
      "url": "https://vhcalnplci:8000",
      "username": "developer",
      "password": "secret",
      "client": "001",
      "language": "EN",
      "allowSelfSigned": true
    }
  }
}
```
url and username are mandatory, password can be left blank. Might need other parameters

**Comment by KaiMildner** [comment]
Ah. Ok. thank you.

**Comment by marcellourbani** [comment]
Closed
Let me know if you have further issues
