### ISSUE TITLE
Failed to connect to <SID>:Error: read ECONNRESET

### ISSUE THREAD

**Issue by qdforbetter** [marcellourbani/vscode_abap_remote_fs#98]
Hello Marc,

I followed your "getting start" at step 4-ii,  after select the command "ABAPfs connect...."
error will be pop up as tittle:  Failed to connect to <SID>:Error: read ECONNRESET

is there something wrong in my SAP configuration? the system can be add into Eclipse by following the SAP ADT guidance. 
Thank you very much.

**Comment by qdforbetter** [comment]
> Hello Marc,
> 
> I followed your "getting start" at step 4-ii, after select the command "ABAPfs connect...."
> error will be pop up as tittle: Failed to connect to :Error: read ECONNRESET
> 
> is there something wrong in my SAP configuration? the system can be add into Eclipse by following the SAP ADT guidance.
> Thank you very much.

**Comment by qdforbetter** [comment]
wrong click...
i found it might be caused by "customCA" in setting.json,
however, i could not found <myCA>.pem ....

**Comment by marcellourbani** [comment]
Hey, sorry for the delay, for some reason I missed this (was on holiday)
Eclipse works over RFC, this uses HTTP(S), so the connectivity requirements are different.

If you can run say fiori apps, using the same URL base should work i.e. my launchpad is https://vhcalnplci.abap.local:44300/sap/bc/ui2/flp, my config will look like:
```json
{
    "abapfs.remote": {
        "vhcalnplci": {
            "url": "https://vhcalnplci.abap.local:44300",
            "username": "developer",
            "password": "",
            "allowSelfSigned": true,
            "client": "001",
            "sapGui": {
                "server": "vhcalnplci.abap.local"
            }
        }
    }
}
```
... and an URL like https://vhcalnplci.abap.local:44300/sap/bc/adt/discovery should download a valid xml document

Notes: customCA is safer than allowSelfSigned but a bit of a pain (you need to set up the path to the .pem file), allowSelfSigned is a decent compromise

**Comment by qdforbetter** [comment]
Hi Marc,

I am sorry that i didn't set he email alert of replying, that's why i didn't know you replied on this. 
Thank you sooooo much.

My vsCode is working fine now it can display my local object and others. I use the allowSelfSigned parameter in "setings.json", cause i didn't know where i can find my pem file. Maybe I need some OS authorization to find the pem file which SAP system installed.

thanks again.

**Comment by marcellourbani** [comment]
I think you can extract t from you browser if you really care
